// Code generated by soapbox. DO NOT EDIT.

package rbacauthorizer

import (
	"k8s.io/api/rbac/v1"
	"monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer"
	"monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/user"
	"monis.app/kk/rbac_authorizer/internal/kk/pkg/registry/rbac/validation"
	"monis.app/kk/rbac_authorizer/internal/kk/plugin/pkg/auth/authorizer/rbac"
)

// Attributes is generated by soapbox from the module-local compatibility
// interface
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.Attributes.
// It is an alias, so the two names denote one type.
type Attributes = authorizer.Attributes

// AttributesRecord is generated by soapbox from the module-local
// compatibility type
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.AttributesRecord.
// It is an alias, so the two names denote one type.
type AttributesRecord = authorizer.AttributesRecord

// AuthorizationRuleResolver is generated by soapbox from the upstream
// interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.AuthorizationRuleResolver,
// which this module relocated to internal/kk/pkg/registry/rbac/validation.
// It is an alias, so the two names denote one type.
type AuthorizationRuleResolver = validation.AuthorizationRuleResolver

// Authorizer is generated by soapbox from the module-local compatibility
// interface
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.Authorizer.
// It is an alias, so the two names denote one type.
type Authorizer = authorizer.Authorizer

// ClusterRoleBindingLister is generated by soapbox from the upstream
// interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.ClusterRoleBindingLister,
// which this module relocated to internal/kk/pkg/registry/rbac/validation.
// It is an alias, so the two names denote one type.
type ClusterRoleBindingLister = validation.ClusterRoleBindingLister

// ClusterRoleBindingListerFromLister is generated by soapbox from the
// upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.ClusterRoleBindingLister,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac. It is an alias, so the two
// names denote one type.
type ClusterRoleBindingListerFromLister = rbac.ClusterRoleBindingLister

// ClusterRoleGetter is generated by soapbox from the upstream interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.ClusterRoleGetter, which
// this module relocated to internal/kk/pkg/registry/rbac/validation. It is
// an alias, so the two names denote one type.
type ClusterRoleGetter = validation.ClusterRoleGetter

// ClusterRoleGetterFromLister is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.ClusterRoleGetter, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type ClusterRoleGetterFromLister = rbac.ClusterRoleGetter

// Decision is generated by soapbox from the module-local compatibility type
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.Decision.
// It is an alias, so the two names denote one type.
type Decision = authorizer.Decision

// DecisionAllow is generated by soapbox from the module-local compatibility
// const
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.DecisionAllow.
const DecisionAllow = authorizer.DecisionAllow

// DecisionDeny is generated by soapbox from the module-local compatibility
// const
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.DecisionDeny.
const DecisionDeny = authorizer.DecisionDeny

// DecisionNoOpinion is generated by soapbox from the module-local
// compatibility const
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.DecisionNoOpinion.
const DecisionNoOpinion = authorizer.DecisionNoOpinion

// DefaultNonResourceRuleInfo is generated by soapbox from the module-local
// compatibility type
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.DefaultNonResourceRuleInfo.
// It is an alias, so the two names denote one type.
type DefaultNonResourceRuleInfo = authorizer.DefaultNonResourceRuleInfo

// DefaultResourceRuleInfo is generated by soapbox from the module-local
// compatibility type
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.DefaultResourceRuleInfo.
// It is an alias, so the two names denote one type.
type DefaultResourceRuleInfo = authorizer.DefaultResourceRuleInfo

// DefaultRuleResolver is generated by soapbox from the upstream type
// k8s.io/kubernetes/pkg/registry/rbac/validation.DefaultRuleResolver, which
// this module relocated to internal/kk/pkg/registry/rbac/validation. It is
// an alias, so the two names denote one type.
type DefaultRuleResolver = validation.DefaultRuleResolver

// DefaultUserInfo is generated by soapbox from the module-local
// compatibility type
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/user.DefaultInfo.
// It is an alias, so the two names denote one type.
type DefaultUserInfo = user.DefaultInfo

// New is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.New, which this module
// relocated to internal/kk/plugin/pkg/auth/authorizer/rbac.
func New(roles RoleGetter, roleBindings RoleBindingLister, clusterRoles ClusterRoleGetter, clusterRoleBindings ClusterRoleBindingLister) *RBACAuthorizer {
	return rbac.New(roles, roleBindings, clusterRoles, clusterRoleBindings)
}

// NewDefaultRuleResolver is generated by soapbox from the upstream func
// k8s.io/kubernetes/pkg/registry/rbac/validation.NewDefaultRuleResolver,
// which this module relocated to internal/kk/pkg/registry/rbac/validation.
func NewDefaultRuleResolver(roleGetter RoleGetter, roleBindingLister RoleBindingLister, clusterRoleGetter ClusterRoleGetter, clusterRoleBindingLister ClusterRoleBindingLister) *DefaultRuleResolver {
	return validation.NewDefaultRuleResolver(roleGetter, roleBindingLister, clusterRoleGetter, clusterRoleBindingLister)
}

// NewSubjectAccessEvaluator is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.NewSubjectAccessEvaluator,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac.
func NewSubjectAccessEvaluator(roles RoleGetter, roleBindings RoleBindingLister, clusterRoles ClusterRoleGetter, clusterRoleBindings ClusterRoleBindingLister, superUser string) *SubjectAccessEvaluator {
	return rbac.NewSubjectAccessEvaluator(roles, roleBindings, clusterRoles, clusterRoleBindings, superUser)
}

// NonResourceRuleInfo is generated by soapbox from the module-local
// compatibility interface
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.NonResourceRuleInfo.
// It is an alias, so the two names denote one type.
type NonResourceRuleInfo = authorizer.NonResourceRuleInfo

// RBACAuthorizer is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RBACAuthorizer, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type RBACAuthorizer = rbac.RBACAuthorizer

// RequestToRuleMapper is generated by soapbox from the upstream interface
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RequestToRuleMapper,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac. It is an alias, so the two
// names denote one type.
type RequestToRuleMapper = rbac.RequestToRuleMapper

// ResourceRuleInfo is generated by soapbox from the module-local
// compatibility interface
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.ResourceRuleInfo.
// It is an alias, so the two names denote one type.
type ResourceRuleInfo = authorizer.ResourceRuleInfo

// RoleBindingLister is generated by soapbox from the upstream interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.RoleBindingLister, which
// this module relocated to internal/kk/pkg/registry/rbac/validation. It is
// an alias, so the two names denote one type.
type RoleBindingLister = validation.RoleBindingLister

// RoleBindingListerFromLister is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleBindingLister, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type RoleBindingListerFromLister = rbac.RoleBindingLister

// RoleGetter is generated by soapbox from the upstream interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.RoleGetter, which this
// module relocated to internal/kk/pkg/registry/rbac/validation. It is an
// alias, so the two names denote one type.
type RoleGetter = validation.RoleGetter

// RoleGetterFromLister is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleGetter, which this
// module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It is an
// alias, so the two names denote one type.
type RoleGetterFromLister = rbac.RoleGetter

// RoleToRuleMapper is generated by soapbox from the upstream interface
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleToRuleMapper, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type RoleToRuleMapper = rbac.RoleToRuleMapper

// RuleAllows is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RuleAllows, which this
// module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac.
func RuleAllows(requestAttributes Attributes, rule *v1.PolicyRule) bool {
	return rbac.RuleAllows(requestAttributes, rule)
}

// RuleResolver is generated by soapbox from the module-local compatibility
// interface
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer.RuleResolver.
// It is an alias, so the two names denote one type.
type RuleResolver = authorizer.RuleResolver

// RulesAllow is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RulesAllow, which this
// module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac.
func RulesAllow(requestAttributes Attributes, rules ...v1.PolicyRule) bool {
	return rbac.RulesAllow(requestAttributes, rules...)
}

// SubjectAccessEvaluator is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.SubjectAccessEvaluator,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac. It is an alias, so the two
// names denote one type.
type SubjectAccessEvaluator = rbac.SubjectAccessEvaluator

// SubjectLocator is generated by soapbox from the upstream interface
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.SubjectLocator, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type SubjectLocator = rbac.SubjectLocator

// UserInfo is generated by soapbox from the module-local compatibility
// interface
// monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/user.Info. It is
// an alias, so the two names denote one type.
type UserInfo = user.Info
