// Code generated by soapbox. DO NOT EDIT.

package rbacauthorizer

import (
	"k8s.io/api/rbac/v1"
	"k8s.io/apiserver/pkg/authorization/authorizer"
	"monis.app/kk/rbac_authorizer/internal/kk/pkg/registry/rbac/validation"
	"monis.app/kk/rbac_authorizer/internal/kk/plugin/pkg/auth/authorizer/rbac"
)

// AuthorizationRuleResolver is generated by soapbox from the upstream
// interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.AuthorizationRuleResolver,
// which this module relocated to internal/kk/pkg/registry/rbac/validation.
// It is an alias, so the two names denote one type.
type AuthorizationRuleResolver = validation.AuthorizationRuleResolver

// ClusterRoleBindingLister is generated by soapbox from the upstream
// interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.ClusterRoleBindingLister,
// which this module relocated to internal/kk/pkg/registry/rbac/validation.
// It is an alias, so the two names denote one type.
type ClusterRoleBindingLister = validation.ClusterRoleBindingLister

// ClusterRoleBindingListerFromLister is generated by soapbox from the
// upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.ClusterRoleBindingLister,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac. It is an alias, so the two
// names denote one type.
type ClusterRoleBindingListerFromLister = rbac.ClusterRoleBindingLister

// ClusterRoleGetter is generated by soapbox from the upstream interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.ClusterRoleGetter, which
// this module relocated to internal/kk/pkg/registry/rbac/validation. It is
// an alias, so the two names denote one type.
type ClusterRoleGetter = validation.ClusterRoleGetter

// ClusterRoleGetterFromLister is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.ClusterRoleGetter, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type ClusterRoleGetterFromLister = rbac.ClusterRoleGetter

// DefaultRuleResolver is generated by soapbox from the upstream type
// k8s.io/kubernetes/pkg/registry/rbac/validation.DefaultRuleResolver, which
// this module relocated to internal/kk/pkg/registry/rbac/validation. It is
// an alias, so the two names denote one type.
type DefaultRuleResolver = validation.DefaultRuleResolver

// New is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.New, which this module
// relocated to internal/kk/plugin/pkg/auth/authorizer/rbac.
func New(roles RoleGetter, roleBindings RoleBindingLister, clusterRoles ClusterRoleGetter, clusterRoleBindings ClusterRoleBindingLister) *RBACAuthorizer {
	return rbac.New(roles, roleBindings, clusterRoles, clusterRoleBindings)
}

// NewDefaultRuleResolver is generated by soapbox from the upstream func
// k8s.io/kubernetes/pkg/registry/rbac/validation.NewDefaultRuleResolver,
// which this module relocated to internal/kk/pkg/registry/rbac/validation.
func NewDefaultRuleResolver(roleGetter RoleGetter, roleBindingLister RoleBindingLister, clusterRoleGetter ClusterRoleGetter, clusterRoleBindingLister ClusterRoleBindingLister) *DefaultRuleResolver {
	return validation.NewDefaultRuleResolver(roleGetter, roleBindingLister, clusterRoleGetter, clusterRoleBindingLister)
}

// NewSubjectAccessEvaluator is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.NewSubjectAccessEvaluator,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac.
func NewSubjectAccessEvaluator(roles RoleGetter, roleBindings RoleBindingLister, clusterRoles ClusterRoleGetter, clusterRoleBindings ClusterRoleBindingLister, superUser string) *SubjectAccessEvaluator {
	return rbac.NewSubjectAccessEvaluator(roles, roleBindings, clusterRoles, clusterRoleBindings, superUser)
}

// RBACAuthorizer is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RBACAuthorizer, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type RBACAuthorizer = rbac.RBACAuthorizer

// RequestToRuleMapper is generated by soapbox from the upstream interface
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RequestToRuleMapper,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac. It is an alias, so the two
// names denote one type.
type RequestToRuleMapper = rbac.RequestToRuleMapper

// RoleBindingLister is generated by soapbox from the upstream interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.RoleBindingLister, which
// this module relocated to internal/kk/pkg/registry/rbac/validation. It is
// an alias, so the two names denote one type.
type RoleBindingLister = validation.RoleBindingLister

// RoleBindingListerFromLister is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleBindingLister, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type RoleBindingListerFromLister = rbac.RoleBindingLister

// RoleGetter is generated by soapbox from the upstream interface
// k8s.io/kubernetes/pkg/registry/rbac/validation.RoleGetter, which this
// module relocated to internal/kk/pkg/registry/rbac/validation. It is an
// alias, so the two names denote one type.
type RoleGetter = validation.RoleGetter

// RoleGetterFromLister is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleGetter, which this
// module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It is an
// alias, so the two names denote one type.
type RoleGetterFromLister = rbac.RoleGetter

// RoleToRuleMapper is generated by soapbox from the upstream interface
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RoleToRuleMapper, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type RoleToRuleMapper = rbac.RoleToRuleMapper

// RuleAllows is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RuleAllows, which this
// module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac.
func RuleAllows(requestAttributes authorizer.Attributes, rule *v1.PolicyRule) bool {
	return rbac.RuleAllows(requestAttributes, rule)
}

// RulesAllow is generated by soapbox from the upstream func
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.RulesAllow, which this
// module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac.
func RulesAllow(requestAttributes authorizer.Attributes, rules ...v1.PolicyRule) bool {
	return rbac.RulesAllow(requestAttributes, rules...)
}

// SubjectAccessEvaluator is generated by soapbox from the upstream type
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.SubjectAccessEvaluator,
// which this module relocated to
// internal/kk/plugin/pkg/auth/authorizer/rbac. It is an alias, so the two
// names denote one type.
type SubjectAccessEvaluator = rbac.SubjectAccessEvaluator

// SubjectLocator is generated by soapbox from the upstream interface
// k8s.io/kubernetes/plugin/pkg/auth/authorizer/rbac.SubjectLocator, which
// this module relocated to internal/kk/plugin/pkg/auth/authorizer/rbac. It
// is an alias, so the two names denote one type.
type SubjectLocator = rbac.SubjectLocator
