// Code generated by soapbox. DO NOT EDIT.

// Package rbacauthorizer provides the Kubernetes RBAC authorizer as an
// independently consumable Go module.
//
// The code behind this package is copied from k8s.io/kubernetes at commit
// 24e2b02af5543d7910c2bb074c7264df5a8f0467 and modified. This module is not
// a Kubernetes release and is not endorsed by or affiliated with that
// project. See the NOTICE file for the full attribution and the record of
// what was changed.
//
// Everything this package exposes is generated from the relocated upstream
// declarations by aliases and forwarding functions, so the published types
// are the upstream types rather than copies of them. Nothing below
// internal/kk is part of the public API, and Go will not permit importing it
// from another module.
package rbacauthorizer
