// Code generated by soapbox. DO NOT EDIT.

package rbacauthorizer

import (
	"monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/authorizer"
)

// These assertions prove that the published types implement the module-local
// compatibility interfaces selected by the profile. They establish internal
// consistency only and make no interoperability claim about
// k8s.io/apiserver.
var (
	_ authorizer.Authorizer   = (*RBACAuthorizer)(nil)
	_ authorizer.RuleResolver = (*RBACAuthorizer)(nil)
)
