// Code generated by soapbox. DO NOT EDIT.

package rbacauthorizer

import (
	"k8s.io/apiserver/pkg/authorization/authorizer"
)

// These assertions prove that the published types implement the upstream
// interfaces the relocated code was written against. The interfaces are the
// real ones from their own modules rather than copies, so an assertion here
// is a statement about interoperability with the wider ecosystem and not
// about this module's internal consistency.
var (
	_ authorizer.Authorizer   = (*RBACAuthorizer)(nil)
	_ authorizer.RuleResolver = (*RBACAuthorizer)(nil)
)
