package facade_test

import (
	"errors"
	"maps"
	"slices"
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/facade"
)

// TestManifestSurvivesPrune is the check the whole prune argument rests on.
//
// Pruning removes upstream files from the relocated packages, and the claim
// that a particular prune is safe is exactly the claim that the published API
// is the same afterwards. Comparing the manifest from before and after is how
// that claim is checked rather than asserted, and the generated bytes are
// compared too, because a facade that produced the same API through different
// source would still churn every release.
func TestManifestSurvivesPrune(t *testing.T) {
	t.Parallel()
	prePrune := maps.Clone(generatedModuleFiles)
	prePrune[internalPrefix+"/pkg/registry/rbac/validation/internal_version_adapter.go"] = `package validation

import (
	rbacv1 "example.com/api/rbac/v1"
)

// LegacyAdapter is the kind of declaration a prune removes: nothing the
// published surface names reaches it.
type LegacyAdapter struct {
	Rules []rbacv1.PolicyRule
}

func NewLegacyAdapter() *LegacyAdapter { return &LegacyAdapter{} }
`

	before := generate(t, newFixture(t, prePrune), rbacSpec())
	after := generate(t, newRBACFixture(t), rbacSpec())

	if differences := facade.Diff(before.Manifest, after.Manifest); len(differences) != 0 {
		for _, difference := range differences {
			t.Errorf("prune changed the published API: %v", difference)
		}
	}
	for i, file := range before.Files {
		if string(file.Contents) != string(after.Files[i].Contents) {
			t.Errorf("prune changed the generated %s\nbefore:\n%s\nafter:\n%s",
				file.Path, file.Contents, after.Files[i].Contents)
		}
	}
}

// TestManifestReportsAPIChange proves the comparison is not vacuous: a change
// the compiler would accept still shows up as a difference.
//
// Each case is a real way an upstream bump breaks consumers without breaking
// the build of this module: a method gains a parameter, a struct loses a field,
// a constant's value moves.
func TestManifestReportsAPIChange(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name    string
		find    string
		replace string
		entry   string
		want    string
	}{
		{
			name:    "interface method gains a parameter",
			find:    "ListRoleBindings(ctx context.Context, namespace string) ([]*rbacv1.RoleBinding, error)",
			replace: "ListRoleBindings(ctx context.Context, namespace string, selector string) ([]*rbacv1.RoleBinding, error)",
			entry:   "RoleBindingLister",
			want:    "func(context.Context, string, string)",
		},
		{
			name:    "struct loses an exported field",
			find:    "type RoleGetter struct {\n\tLister func(namespace string) ([]*rbacv1.Role, error)\n}",
			replace: "type RoleGetter struct {\n\tlister func(namespace string) ([]*rbacv1.Role, error)\n}",
			entry:   "RoleGetterFromLister",
			want:    "field Lister",
		},
		{
			name:    "constant changes value",
			find:    "const PolicyRuleLimit = 64",
			replace: "const PolicyRuleLimit = 128",
			entry:   "PolicyRuleLimit",
			want:    "value: 128",
		},
		{
			// The qualified name and the members are both unchanged here, so
			// only the recorded underlying type shows that a consumer's
			// existing conversions and arithmetic no longer compile.
			name:    "defined type changes its underlying type",
			find:    "type Decision int",
			replace: "type Decision int64",
			entry:   "Decision",
			want:    "underlying: int64",
		},
	}
	base := generate(t, newRBACFixture(t), rbacSpec())

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			files := maps.Clone(generatedModuleFiles)
			replaced := false
			for name, source := range files {
				if strings.Contains(source, test.find) {
					files[name] = strings.Replace(source, test.find, test.replace, 1)
					replaced = true
				}
			}
			if !replaced {
				t.Fatalf("fixture does not contain %q", test.find)
			}

			changed := generate(t, newFixture(t, files), rbacSpec())
			if base.Manifest.Equal(changed.Manifest) {
				t.Fatalf("manifest did not change")
			}
			differences := facade.Diff(base.Manifest, changed.Manifest)
			if len(differences) != 1 {
				t.Fatalf("manifest reports %d differences, want exactly the one that changed: %v", len(differences), differences)
			}
			if differences[0].Name != test.entry {
				t.Errorf("difference names %s, want %s", differences[0].Name, test.entry)
			}
			if !strings.Contains(differences[0].String(), test.want) {
				t.Errorf("difference does not mention %q:\n%s", test.want, differences[0])
			}
		})
	}
}

// TestManifestIgnoresParameterNames is the design decision this comparison
// rests on.
//
// Go's notion of API identity does not include parameter or result names, so an
// upstream rename changes nothing a consumer can call. A manifest that recorded
// them would report such a rename as an API difference and would fail a
// pre-prune against post-prune comparison over a change that is not one.
func TestManifestIgnoresParameterNames(t *testing.T) {
	t.Parallel()
	base := generate(t, newRBACFixture(t), rbacSpec())

	files := maps.Clone(generatedModuleFiles)
	renamed := false
	for name, source := range files {
		if strings.Contains(source, "ListRoleBindings(ctx context.Context, namespace string)") {
			files[name] = strings.ReplaceAll(source,
				"ListRoleBindings(ctx context.Context, namespace string)",
				"ListRoleBindings(c context.Context, ns string)")
			renamed = true
		}
	}
	if !renamed {
		t.Fatalf("fixture does not contain the parameters to rename")
	}

	after := generate(t, newFixture(t, files), rbacSpec())
	if differences := facade.Diff(base.Manifest, after.Manifest); len(differences) != 0 {
		t.Errorf("renaming a parameter changed the manifest: %v", differences)
	}
	// The generated file keeps the upstream names, because they are the only
	// documentation a signature carries.
	if source := fileNamed(t, after, "authorizer.go"); !strings.Contains(source, "roleBindings RoleBindingLister") {
		t.Errorf("generated facade dropped its parameter names\n%s", source)
	}
}

// TestManifestCheckAgainstBaseline covers the blocking seam a caller puts
// between generating a facade and publishing it.
func TestManifestCheckAgainstBaseline(t *testing.T) {
	t.Parallel()
	base := generate(t, newRBACFixture(t), rbacSpec()).Manifest

	if err := base.CheckAgainst(base); err != nil {
		t.Errorf("a manifest does not check against itself: %v", err)
	}

	changed := base
	changed.Entries = slices.Clone(base.Entries)
	changed.Entries = slices.DeleteFunc(changed.Entries, func(entry facade.Entry) bool { return entry.Name == "New" })
	err := changed.CheckAgainst(base)
	if !errors.Is(err, facade.ErrManifestChanged) {
		t.Fatalf("check error is %v, want ErrManifestChanged", err)
	}
	// The error carries the differences, so a caller that only reports the
	// error still tells the operator what changed.
	if !strings.Contains(err.Error(), "removed New") {
		t.Errorf("check error %v does not name what changed", err)
	}
}

// TestDiffReportsAdditionsRemovalsAndHeaders covers the comparison on its own,
// without a module, so the ordering and the empty cases are pinned directly.
func TestDiffReportsAdditionsRemovalsAndHeaders(t *testing.T) {
	t.Parallel()
	entry := func(name, target string) facade.Entry {
		return facade.Entry{Name: name, Kind: facade.KindType, Target: target, Type: target}
	}
	base := facade.Manifest{
		Module:  "monis.app/kk/rbac_authorizer",
		Package: "rbacauthorizer",
		Entries: []facade.Entry{entry("Alpha", "x/y.Alpha"), entry("Beta", "x/y.Beta")},
	}

	tests := []struct {
		name  string
		after facade.Manifest
		want  []string
	}{
		{name: "identical manifests do not differ", after: base},
		{
			name: "a removed export is reported",
			after: facade.Manifest{Module: base.Module, Package: base.Package,
				Entries: []facade.Entry{entry("Alpha", "x/y.Alpha")}},
			want: []string{"Beta"},
		},
		{
			name: "an added export is reported",
			after: facade.Manifest{Module: base.Module, Package: base.Package,
				Entries: []facade.Entry{entry("Alpha", "x/y.Alpha"), entry("Beta", "x/y.Beta"), entry("Gamma", "x/y.Gamma")}},
			want: []string{"Gamma"},
		},
		{
			name: "a retargeted export is reported",
			after: facade.Manifest{Module: base.Module, Package: base.Package,
				Entries: []facade.Entry{entry("Alpha", "x/z.Alpha"), entry("Beta", "x/y.Beta")}},
			want: []string{"Alpha"},
		},
		{
			name: "differences are ordered by name",
			after: facade.Manifest{Module: base.Module, Package: base.Package,
				Entries: []facade.Entry{entry("Gamma", "x/y.Gamma"), entry("Delta", "x/y.Delta")}},
			want: []string{"Alpha", "Beta", "Delta", "Gamma"},
		},
		{
			name:  "a different module is reported before the exports",
			after: facade.Manifest{Module: "other/module", Package: base.Package, Entries: base.Entries},
			want:  []string{"module"},
		},
		{
			name:  "a different package is reported",
			after: facade.Manifest{Module: base.Module, Package: "other", Entries: base.Entries},
			want:  []string{"package"},
		},
	}
	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			differences := facade.Diff(base, test.after)
			names := make([]string, len(differences))
			for i, difference := range differences {
				names[i] = difference.Name
			}
			if strings.Join(names, ",") != strings.Join(test.want, ",") {
				t.Errorf("differences are %v, want %v", names, test.want)
			}
			if base.Equal(test.after) != (len(test.want) == 0) {
				t.Errorf("Equal reports %v while Diff reports %d differences", base.Equal(test.after), len(differences))
			}
		})
	}
}

// TestManifestRenderIsStable proves the rendered manifest is a deterministic
// function of the manifest, which is what lets it be committed as a report.
func TestManifestRenderIsStable(t *testing.T) {
	t.Parallel()
	result := generate(t, newRBACFixture(t), rbacSpec())
	rendered := result.Manifest.Render()

	if rendered != result.Manifest.Render() {
		t.Errorf("rendering the same manifest twice produced different text")
	}
	for _, want := range []string{
		"soapbox facade manifest",
		"module: " + generatedModule,
		"package: rbacauthorizer",
		// Full package paths rather than local aliases, so a type that moved
		// between packages never compares equal to the one it replaced.
		"target: " + generatedModule + "/" + internalPrefix + "/plugin/pkg/auth/authorizer/rbac.RBACAuthorizer",
		// Parameter names are absent: API identity does not include them.
		"method Authorize func(context.Context, " + authorizerPkg + ".Attributes)",
	} {
		if !strings.Contains(rendered, want) {
			t.Errorf("rendered manifest does not contain %q\n%s", want, rendered)
		}
	}

	// Entries are in facade name order, which is the order a reader compares
	// two releases in.
	previous := ""
	for _, entry := range result.Manifest.Entries {
		if entry.Name <= previous {
			t.Errorf("manifest entry %s follows %s, which is not sorted order", entry.Name, previous)
		}
		previous = entry.Name
	}
}
