/*
Copyright 2014 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by soapbox. DO NOT EDIT.
// This module-local compatibility declaration is intentionally not type-compatible with k8s.io/apiserver.
// Upstream repository: https://github.com/kubernetes/kubernetes.git
// Upstream path: staging/src/k8s.io/apiserver/pkg/authentication/serviceaccount/util.go
// Upstream commit: 24e2b02af5543d7910c2bb074c7264df5a8f0467

package serviceaccount

import "strings"

const (
	ServiceAccountUsernamePrefix = "system:serviceaccount:"
	ServiceAccountUsernameSeparator = ":"
)

// MatchesUsername compares a service-account identity without allocation.
func MatchesUsername(namespace, name, username string) bool {
	if !strings.HasPrefix(username, ServiceAccountUsernamePrefix) {
		return false
	}
	username = username[len(ServiceAccountUsernamePrefix):]
	if !strings.HasPrefix(username, namespace) {
		return false
	}
	username = username[len(namespace):]
	if !strings.HasPrefix(username, ServiceAccountUsernameSeparator) {
		return false
	}
	return username[len(ServiceAccountUsernameSeparator):] == name
}
