package rewrite_test

import (
	"errors"
	"slices"
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/rewrite"
)

// prunedTargets reports a dangling callback that treats the named marker values
// as pruned, which is how the caller tells the rewrite that a generator's input
// or output no longer exists.
func prunedTargets(values ...string) func(rewrite.Directive) bool {
	return func(directive rewrite.Directive) bool {
		return slices.Contains(values, directive.Value)
	}
}

func TestDirectiveRules(t *testing.T) {
	t.Parallel()

	// The retained upstream doc.go of pkg/apis/rbac/v1, which is the file the
	// RBAC profile's marker handling was written for.
	docFile := "/*\nCopyright 2016 The Kubernetes Authors.\n*/\n\n" +
		"// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/rbac\n" +
		"// +k8s:conversion-gen-external-types=k8s.io/api/rbac/v1\n" +
		"// +k8s:deepcopy-gen=package\n" +
		"// +groupName=rbac.authorization.k8s.io\n" +
		"\n" +
		"package v1\n"

	tests := []struct {
		name     string
		in       string
		dangling func(rewrite.Directive) bool
		want     string
	}{
		{
			name: "an input marker is rewritten while its package survives",
			in:   docFile,
			want: "/*\nCopyright 2016 The Kubernetes Authors.\n*/\n\n" +
				"// +k8s:conversion-gen=monis.app/kk/rbac_authorizer/internal/kk/pkg/apis/rbac\n" +
				"// +k8s:conversion-gen-external-types=k8s.io/api/rbac/v1\n" +
				"// +k8s:deepcopy-gen=package\n" +
				"// +groupName=rbac.authorization.k8s.io\n" +
				"\n" +
				"package v1\n",
		},
		{
			name:     "a dangling input marker is removed and the rest survives",
			in:       docFile,
			dangling: prunedTargets("k8s.io/kubernetes/pkg/apis/rbac", "package"),
			want: "/*\nCopyright 2016 The Kubernetes Authors.\n*/\n\n" +
				"// +k8s:conversion-gen-external-types=k8s.io/api/rbac/v1\n" +
				"// +groupName=rbac.authorization.k8s.io\n" +
				"\n" +
				"package v1\n",
		},
		{
			name: "go:generate is removed",
			in: "package v1\n\n" +
				"//go:generate deepcopy-gen -i ./...\n" +
				"type Rule struct{}\n",
			want: "package v1\n\n" +
				"type Rule struct{}\n",
		},
		{
			name: "a comma separated marker maps only its eligible elements",
			in: "// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/rbac,k8s.io/api/rbac/v1\n" +
				"package v1\n",
			want: "// +k8s:conversion-gen=monis.app/kk/rbac_authorizer/internal/kk/pkg/apis/rbac,k8s.io/api/rbac/v1\n" +
				"package v1\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			options := testOptions()
			options.Directives.Dangling = test.dangling
			result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", test.in), options)
			if err != nil {
				t.Fatalf("rewrite: %v", err)
			}
			if got := string(result.Contents); got != test.want {
				t.Errorf("rewrote to:\n%s\nwant:\n%s", got, test.want)
			}
		})
	}
}

// TestDirectivesLeftAlone covers the markers and directives that must survive
// untouched. Each one changes how the file builds, what API it declares, or
// what type it pairs with, so removing or rewriting it is a behaviour change
// disguised as a text edit.
func TestDirectivesLeftAlone(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   string
	}{
		{
			name: "modern build constraint",
			in:   "//go:build linux && !race\n\npackage v1\n",
		},
		{
			name: "legacy build constraint",
			in:   "// +build linux,!race\n\npackage v1\n",
		},
		{
			name: "go:embed directive",
			in: "package v1\n\n" +
				"import _ \"embed\"\n\n" +
				"//go:embed schema.json\n" +
				"var schema string\n",
		},
		{
			name: "compiler directives",
			in: "package v1\n\n" +
				"//go:noinline\n" +
				"//go:nosplit\n" +
				"func probe() {}\n",
		},
		{
			name: "group name and external type markers",
			in: "// +groupName=rbac.authorization.k8s.io\n" +
				"// +k8s:conversion-gen-external-types=k8s.io/api/rbac/v1\n" +
				"package v1\n",
		},
		{
			name: "unknown markers fall through to keep",
			in: "package v1\n\n" +
				"// +optional\n" +
				"// +listType=atomic\n" +
				"// +k8s:some-future-generator=whatever\n" +
				"type Rule struct{}\n",
		},
		{
			name: "a generated file marker",
			in: "//go:build !ignore_autogenerated\n\n" +
				"// Code generated by deepcopy-gen. DO NOT EDIT.\n\n" +
				"package v1\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			// Everything is reported as dangling, so only the protection itself
			// can keep these directives in the file.
			options := testOptions()
			options.Directives.Dangling = func(rewrite.Directive) bool { return true }

			result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", test.in), options)
			if err != nil {
				t.Fatalf("rewrite: %v", err)
			}
			if got := string(result.Contents); got != test.in {
				t.Errorf("rewrote to:\n%s\nwant it unchanged:\n%s", got, test.in)
			}
		})
	}
}

// TestDirectiveAfterCodeIsKept covers the one case where removing a directive
// would delete code: a marker written at the end of a line that also holds a
// declaration. Deleting that line would delete the declaration with it.
func TestDirectiveAfterCodeIsKept(t *testing.T) {
	t.Parallel()

	in := "package v1\n\n" +
		"type Rule struct{} //go:generate deepcopy-gen\n"

	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/types.go", in), testOptions())
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}
	if got := string(result.Contents); got != in {
		t.Errorf("rewrote to:\n%s\nwant it unchanged:\n%s", got, in)
	}
}

// TestMarkerRemovalIsReported asserts that every removed marker reaches the
// change report, which is what the provenance record renders. A silent removal
// would be a behaviour change nobody could audit.
func TestMarkerRemovalIsReported(t *testing.T) {
	t.Parallel()

	in := "// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/rbac\n" +
		"// +k8s:deepcopy-gen=package\n" +
		"// +groupName=rbac.authorization.k8s.io\n" +
		"\n" +
		"package v1\n"

	options := testOptions()
	options.Directives.Dangling = prunedTargets("k8s.io/kubernetes/pkg/apis/rbac", "package")

	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", in), options)
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}

	var removed []string
	for _, change := range result.Changes {
		if change.Kind == rewrite.ChangeMarkerRemoval {
			removed = append(removed, change.From)
		}
	}
	want := []string{
		"// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/rbac",
		"// +k8s:deepcopy-gen=package",
	}
	if !slices.Equal(removed, want) {
		t.Errorf("reported removals %v, want %v", removed, want)
	}
	for _, change := range result.Changes {
		if change.Line == 0 {
			t.Errorf("change %v carries no line number", change)
		}
	}
}

// TestChangeReportIsOrdered asserts a stable report order, because the report
// is rendered into a committed provenance file and a reordering would show up
// as a diff in every release.
func TestChangeReportIsOrdered(t *testing.T) {
	t.Parallel()

	in := "// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/rbac\n" +
		"package v1\n\n" +
		"import (\n" +
		"\t\"k8s.io/kubernetes/pkg/registry/rbac/validation\"\n" +
		"\t\"k8s.io/kubernetes/pkg/apis/rbac\"\n" +
		")\n\n" +
		"var _ = validation.NewDefaultRuleResolver\n" +
		"var _ rbac.PolicyRule\n"

	options := testOptions()
	options.NoNotice = false

	var first []string
	for range 5 {
		result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", in), options)
		if err != nil {
			t.Fatalf("rewrite: %v", err)
		}
		rendered := make([]string, len(result.Changes))
		for i, change := range result.Changes {
			rendered[i] = change.String()
		}
		if first == nil {
			first = rendered
			continue
		}
		if !slices.Equal(rendered, first) {
			t.Fatalf("report %v, want %v on every run", rendered, first)
		}
	}
	if len(first) != 4 {
		t.Fatalf("reported %d changes, want the notice, the directive, and both imports: %v", len(first), first)
	}
	for i := 1; i < len(first); i++ {
		if lineOfReport(t, first[i-1]) > lineOfReport(t, first[i]) {
			t.Errorf("report is not ordered by line: %v", first)
		}
	}
}

// lineOfReport reads the line number out of a rendered change.
func lineOfReport(t *testing.T, rendered string) int {
	t.Helper()
	_, rest, ok := strings.Cut(rendered, ":")
	if !ok {
		t.Fatalf("rendered change %q has no line", rendered)
	}
	number, _, _ := strings.Cut(rest, " ")
	line := 0
	for _, r := range number {
		if r < '0' || r > '9' {
			t.Fatalf("rendered change %q has no line number", rendered)
		}
		line = line*10 + int(r-'0')
	}
	return line
}

// TestDirectiveRemovalStaysGofmtClean is the shape matrix for directive
// removal.
//
// The generated module is committed and then gated on gofmt, so a removal that
// leaves a blank line where the formatter allows none fails the release rather
// than merely looking untidy. Every input here is asserted to be gofmt clean
// before it is rewritten, because a shape the formatter would already have
// changed proves nothing about the removal.
//
// The positions that allow no blank line were measured against the pinned
// formatter rather than assumed: the two ends of the file, and the two edges of
// a field list or a parenthesized declaration group. A function body, a case
// clause, and a composite literal keep a blank line at their edges, so a
// removal there leaves one behind on purpose.
func TestDirectiveRemovalStaysGofmtClean(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "end of file",
			in:   "package v1\n\nfunc F() {}\n\n//go:generate x\n",
			want: "package v1\n\nfunc F() {}\n",
		},
		{
			name: "file left holding only its package clause",
			in:   "package v1\n\n//go:generate x\n",
			want: "package v1\n",
		},
		{
			name: "start of file",
			in:   "//go:generate x\n\npackage v1\n",
			want: "package v1\n",
		},
		{
			name: "start of file with no blank line",
			in:   "//go:generate x\npackage v1\n",
			want: "package v1\n",
		},
		{
			name: "head of a struct field list",
			in:   "package v1\n\ntype Rule struct {\n\t//go:generate x\n\n\tName string\n}\n",
			want: "package v1\n\ntype Rule struct {\n\tName string\n}\n",
		},
		{
			name: "tail of a struct field list",
			in:   "package v1\n\ntype Rule struct {\n\tName string\n\n\t//go:generate x\n}\n",
			want: "package v1\n\ntype Rule struct {\n\tName string\n}\n",
		},
		{
			name: "sole member of a field list",
			in:   "package v1\n\ntype Rule struct {\n\t//go:generate x\n}\n",
			want: "package v1\n\ntype Rule struct {\n}\n",
		},
		{
			name: "head of an interface",
			in:   "package v1\n\ntype R interface {\n\t//go:generate x\n\n\tName() string\n}\n",
			want: "package v1\n\ntype R interface {\n\tName() string\n}\n",
		},
		{
			name: "head of a declaration group",
			in:   "package v1\n\nvar (\n\t//go:generate x\n\n\tA = 1\n)\n",
			want: "package v1\n\nvar (\n\tA = 1\n)\n",
		},
		{
			name: "tail of a declaration group",
			in:   "package v1\n\nvar (\n\tA = 1\n\n\t//go:generate x\n)\n",
			want: "package v1\n\nvar (\n\tA = 1\n)\n",
		},
		{
			name: "a function body keeps its blank line",
			in:   "package v1\n\nfunc F() {\n\t//go:generate x\n\n\treturn\n}\n",
			want: "package v1\n\nfunc F() {\n\n\treturn\n}\n",
		},
		{
			name: "a case clause keeps its blank line",
			in:   "package v1\n\nfunc F(i int) {\n\tswitch i {\n\tcase 1:\n\t\t//go:generate x\n\n\t\treturn\n\t}\n}\n",
			want: "package v1\n\nfunc F(i int) {\n\tswitch i {\n\tcase 1:\n\n\t\treturn\n\t}\n}\n",
		},
		{
			name: "between declarations",
			in:   "package v1\n\n//go:generate x\n\ntype Rule struct{}\n",
			want: "package v1\n\ntype Rule struct{}\n",
		},
		{
			name: "two blocks separated by a blank line",
			in:   "package v1\n\n//go:generate a\n\n//go:generate b\n\ntype Rule struct{}\n",
			want: "package v1\n\ntype Rule struct{}\n",
		},
		{
			// gofmt drops an empty // from the end of a documentation comment,
			// so the separator that held the prose apart from the directives
			// leaves with them.
			name: "documentation separator left stranded",
			in:   "package v1\n\n// Rule is a rule.\n//\n//go:generate x\ntype Rule struct{}\n",
			want: "package v1\n\n// Rule is a rule.\ntype Rule struct{}\n",
		},
		{
			name: "documentation separator above two directives",
			in:   "package v1\n\n// Rule is a rule.\n//\n//go:generate a\n//go:generate b\ntype Rule struct{}\n",
			want: "package v1\n\n// Rule is a rule.\ntype Rule struct{}\n",
		},
		{
			// The blank line is what keeps the note a floating comment. A
			// removal that absorbed it would hand the note to Rule as its
			// documentation comment, which is a change to the published godoc
			// that no report would mention.
			name: "a floating comment stays detached",
			in:   "package v1\n\n// Floating note.\n//go:generate a\n//go:generate b\n\ntype Rule struct{}\n",
			want: "package v1\n\n// Floating note.\n\ntype Rule struct{}\n",
		},
		{
			name: "a floating comment stays detached after one removal",
			in:   "package v1\n\n// Floating note.\n//go:generate a\n\ntype Rule struct{}\n",
			want: "package v1\n\n// Floating note.\n\ntype Rule struct{}\n",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			assertGofmt(t, []byte(test.in))

			result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/x.go", test.in), testOptions())
			if err != nil {
				t.Fatalf("rewrite: %v", err)
			}
			if got := string(result.Contents); got != test.want {
				t.Errorf("rewrote to:\n%q\nwant:\n%q", got, test.want)
			}
			assertGofmt(t, result.Contents)
		})
	}
}

// TestDirectiveRejectsEmbeddedCarriageReturn covers the offset the Go scanner
// does not give.
//
// A carriage return inside a comment is stripped out of the comment's text, so
// the end position derived from that text is short by one byte for every one
// removed. A value rewrite driven by it would claim one byte too few and weld
// the tail of the old path onto the new one. Under the preserving policy such a
// file reaches the rewrite, so the mismatch is reported rather than edited
// around.
func TestDirectiveRejectsEmbeddedCarriageReturn(t *testing.T) {
	t.Parallel()

	options := testOptions()
	options.LineEndings = rewrite.LineEndingPreserve

	in := "// +k8s:conversion-gen\r=k8s.io/kubernetes/pkg/apis/rbac\npackage v1\n"
	_, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", in), options)
	if !errors.Is(err, rewrite.ErrCarriageReturn) {
		t.Fatalf("rewrite error %v, want %v", err, rewrite.ErrCarriageReturn)
	}
}
