package rewrite_test

import (
	"testing"

	"github.com/enj/soapbox/tools/internal/rewrite"
)

func TestGenerated(t *testing.T) {
	tests := []struct {
		name string
		src  string
		want bool
	}{
		{
			name: "marker before the package clause",
			src:  "// Code generated by deepcopy-gen. DO NOT EDIT.\n\npackage v1\n\nfunc F() {}\n",
			want: true,
		},
		{
			name: "marker below a license header",
			src:  "/*\nCopyright 2016 The Kubernetes Authors.\n*/\n\n// Code generated by conversion-gen. DO NOT EDIT.\n\npackage v1\n",
			want: true,
		},
		{
			name: "marker below a build constraint",
			src:  "//go:build linux\n\n// Code generated by mockgen. DO NOT EDIT.\n\npackage v1\n",
			want: true,
		},
		{
			name: "empty generator name",
			src:  "// Code generated  DO NOT EDIT.\n\npackage v1\n",
			want: true,
		},
		{
			// The convention bounds the search at the package clause, so a file
			// that merely talks about generated code below it is hand written.
			name: "marker after the package clause",
			src:  "package v1\n\n// Code generated by x. DO NOT EDIT.\nfunc F() {}\n",
			want: false,
		},
		{
			// Only a line comment counts. Accepting a block comment would mark
			// files that gofmt, go vet, and every linter treat as hand written.
			name: "marker inside a block comment",
			src:  "/* Code generated by x. DO NOT EDIT. */\npackage v1\n",
			want: false,
		},
		{
			name: "trailing text after the marker",
			src:  "// Code generated by x. DO NOT EDIT. really\npackage v1\n",
			want: false,
		},
		{
			name: "leading text before the marker",
			src:  "// See: Code generated by x. DO NOT EDIT.\npackage v1\n",
			want: false,
		},
		{
			name: "wrong case",
			src:  "// code generated by x. do not edit.\npackage v1\n",
			want: false,
		},
		{
			name: "ordinary source",
			src:  "package v1\n\nfunc F() {}\n",
			want: false,
		},
		{
			// The flag is computed when the closure selects a file, long before
			// anything has proved it compiles, so a broken body must not hide a
			// marker the package clause already bounds.
			name: "marker with an unparsable body",
			src:  "// Code generated by x. DO NOT EDIT.\npackage v1\n\nfunc ( {\n",
			want: true,
		},
		{
			name: "not go source at all",
			src:  "syntax = \"proto2\";\noption go_package = \"v1\";\n",
			want: false,
		},
		{name: "empty file", src: "", want: false},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			if got := rewrite.Generated([]byte(test.src)); got != test.want {
				t.Fatalf("Generated = %t, want %t", got, test.want)
			}
		})
	}
}
