package rewrite_test

import (
	"go/ast"
	"go/build"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/rewrite"
)

// noticedOptions turns the modification notice on.
func noticedOptions() rewrite.Options {
	options := testOptions()
	options.NoNotice = false
	return options
}

// eligibleImport is the one line that makes a file changed, so a notice test
// can concentrate on where the notice lands.
const eligibleImport = "import \"k8s.io/kubernetes/pkg/apis/rbac\"\n"

func TestNoticePlacement(t *testing.T) {
	t.Parallel()

	notice := "// This file was modified by soapbox and is not the upstream original.\n" +
		"// Upstream repository: https://github.com/kubernetes/kubernetes.git\n" +
		"// Upstream path: pkg/apis/rbac/v1/doc.go\n" +
		"// Upstream commit: 0123456789abcdef0123456789abcdef01234567\n" +
		"// Imports under k8s.io/kubernetes were rewritten to monis.app/kk/rbac_authorizer/internal/kk.\n\n"

	tests := []struct {
		name string
		in   string
		want string
	}{
		{
			name: "below a license header",
			in: "/*\nCopyright 2016 The Kubernetes Authors.\n*/\n\n" +
				"package v1\n\n" + eligibleImport,
			want: "/*\nCopyright 2016 The Kubernetes Authors.\n*/\n\n" +
				notice +
				"package v1\n\n" + rewrittenImport,
		},
		{
			name: "above an attached package documentation comment",
			in: "// Package v1 holds the retained helpers.\n" +
				"package v1\n\n" + eligibleImport,
			want: notice +
				"// Package v1 holds the retained helpers.\n" +
				"package v1\n\n" + rewrittenImport,
		},
		{
			name: "below a build constraint",
			in: "//go:build linux\n\n" +
				"package v1\n\n" + eligibleImport,
			want: "//go:build linux\n\n" +
				notice +
				"package v1\n\n" + rewrittenImport,
		},
		{
			name: "below a generated file marker",
			in: "// Code generated by deepcopy-gen. DO NOT EDIT.\n\n" +
				"package v1\n\n" + eligibleImport,
			want: "// Code generated by deepcopy-gen. DO NOT EDIT.\n\n" +
				notice +
				"package v1\n\n" + rewrittenImport,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", test.in), noticedOptions())
			if err != nil {
				t.Fatalf("rewrite: %v", err)
			}
			if got := string(result.Contents); got != test.want {
				t.Errorf("rewrote to:\n%s\nwant:\n%s", got, test.want)
			}
			assertGofmt(t, result.Contents)
		})
	}
}

// rewrittenImport is the eligible import after relocation.
const rewrittenImport = "import \"monis.app/kk/rbac_authorizer/internal/kk/pkg/apis/rbac\"\n"

// TestNoticeKeepsBuildConstraints proves the constraint still selects platforms
// after the notice is inserted, by asking the Go toolchain's own file matcher
// rather than by inspecting the text.
func TestNoticeKeepsBuildConstraints(t *testing.T) {
	t.Parallel()

	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go",
		"//go:build linux\n\npackage v1\n\n"+eligibleImport), noticedOptions())
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "doc.go"), result.Contents, 0o600); err != nil {
		t.Fatalf("write rewritten file: %v", err)
	}
	for _, test := range []struct {
		goos string
		want bool
	}{
		{goos: "linux", want: true},
		{goos: "darwin", want: false},
	} {
		context := build.Default
		context.GOOS = test.goos
		context.GOARCH = "amd64"
		got, err := context.MatchFile(dir, "doc.go")
		if err != nil {
			t.Fatalf("match file for %s: %v", test.goos, err)
		}
		if got != test.want {
			t.Errorf("the rewritten file builds on %s: %t, want %t", test.goos, got, test.want)
		}
	}
}

// TestNoticeKeepsGeneratedMarker proves the marker still identifies the file as
// generated, using the same detection the standard library offers tools.
func TestNoticeKeepsGeneratedMarker(t *testing.T) {
	t.Parallel()

	in := "// Code generated by deepcopy-gen. DO NOT EDIT.\n\npackage v1\n\n" + eligibleImport
	file := goFile("pkg/apis/rbac/v1/zz_generated.deepcopy.go", in)
	file.Generated = true

	result, err := rewrite.GoFile(t.Context(), file, noticedOptions())
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}
	if !ast.IsGenerated(parseForTest(t, result.Contents)) {
		t.Errorf("the rewritten file is no longer recognised as generated:\n%s", result.Contents)
	}
}

// TestNoticeKeepsPackageDocumentation proves the notice does not detach an
// existing documentation comment from its package clause.
func TestNoticeKeepsPackageDocumentation(t *testing.T) {
	t.Parallel()

	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go",
		"// Package v1 holds the retained helpers.\npackage v1\n\n"+eligibleImport), noticedOptions())
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}
	parsed := parseForTest(t, result.Contents)
	if parsed.Doc == nil {
		t.Fatalf("the package documentation was detached:\n%s", result.Contents)
	}
	if got := strings.TrimSpace(parsed.Doc.Text()); got != "Package v1 holds the retained helpers." {
		t.Errorf("package documentation is %q", got)
	}
}

// TestNoticeOnlyOnChangedFiles asserts that a file the engine did not have to
// touch is returned byte for byte. Claiming a modification that never happened
// would put a notice on top of untouched upstream code.
func TestNoticeOnlyOnChangedFiles(t *testing.T) {
	t.Parallel()

	in := "package v1\n\nimport \"k8s.io/api/rbac/v1\"\n\nvar _ = v1.PolicyRule{}\n"
	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go", in), noticedOptions())
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}
	if got := string(result.Contents); got != in {
		t.Errorf("an unchanged file acquired:\n%s", got)
	}
}

func TestNoticeCanBeSuppressed(t *testing.T) {
	t.Parallel()

	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go",
		"package v1\n\n"+eligibleImport), testOptions())
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}
	if strings.Contains(string(result.Contents), "soapbox") {
		t.Errorf("a notice was inserted despite NoNotice:\n%s", result.Contents)
	}
}

// TestNoticeOmitsUnknownProvenance asserts the notice never renders an empty
// claim about where a file came from.
func TestNoticeOmitsUnknownProvenance(t *testing.T) {
	t.Parallel()

	options := noticedOptions()
	options.SourceRepository = ""
	options.SourceSHA = ""

	result, err := rewrite.GoFile(t.Context(), goFile("pkg/apis/rbac/v1/doc.go",
		"package v1\n\n"+eligibleImport), options)
	if err != nil {
		t.Fatalf("rewrite: %v", err)
	}
	got := string(result.Contents)
	for _, unwanted := range []string{"Upstream repository:", "Upstream commit:"} {
		if strings.Contains(got, unwanted) {
			t.Errorf("notice renders an empty %q:\n%s", unwanted, got)
		}
	}
	if !strings.Contains(got, "Upstream path: pkg/apis/rbac/v1/doc.go") {
		t.Errorf("notice lost the upstream path:\n%s", got)
	}
}

// parseForTest parses rewritten output with its comments.
func parseForTest(t *testing.T, src []byte) *ast.File {
	t.Helper()
	parsed, err := parser.ParseFile(token.NewFileSet(), "rewritten.go", src, parser.ParseComments|parser.SkipObjectResolution)
	if err != nil {
		t.Fatalf("parse rewritten file: %v\n%s", err, src)
	}
	return parsed
}
