package generate

import (
	"context"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"

	"github.com/enj/soapbox/tools/internal/config"
	"github.com/enj/soapbox/tools/internal/gocli"
	"github.com/enj/soapbox/tools/internal/modgen"
	"github.com/enj/soapbox/tools/internal/modulegraph"
	"github.com/enj/soapbox/tools/internal/typeswap"
)

// runTypes proves the profile's type substitution against upstream package
// identities.
//
// Which tree the analysis runs over is the whole correctness question here, and
// the answer is the pre-prune upstream source tree rather than either relocated
// module. A profile states its pairing in upstream terms, such as
// k8s.io/kubernetes/pkg/apis/rbac paired with k8s.io/api/rbac/v1, and it is
// making a claim about those two packages. A relocated module has neither: the
// internal package has been rewritten to a path under the generated module, and
// proving something about that path proves it about the engine's own rewriting
// rather than about the upstream code the profile is reasoning over.
//
// The pre-prune tree is used rather than the post-prune one because the internal
// package the pairing names is exactly what pruning removes. Analysing the
// post-prune tree would be asking whether a package that is no longer present is
// substitutable, which every profile would pass for the wrong reason.
func (r *run) runTypes(ctx context.Context) error {
	dir, err := r.prepareUpstreamModule(ctx)
	if err != nil {
		return runtimeError(stageTypes, err)
	}
	// Installing the module and loading the graph are toolchain work: writing
	// files, tidying against a proxy, and type checking. None of it can produce
	// a finding about the profile, so none of it is reported as one.
	if err := r.installUpstreamModule(ctx, dir); err != nil {
		return runtimeError(stageTypes, err)
	}

	graph, err := r.loadUpstreamGraph(ctx, dir)
	if err != nil {
		return runtimeError(stageTypes, err)
	}

	// Relabel is deliberately left zero. The import paths in this graph are
	// already the upstream ones the profile spells, so there is nothing to map,
	// and stating a relabel that does not apply is how a load ends up reporting
	// paths that disagree with the type identities behind them.
	spec := modulegraph.TypeswapSpec{
		Retained:             r.post.Report.Closure.Report.Exact.Packages,
		PrunedFiles:          r.cfg.Prune.Files,
		PublicAPIDifferences: r.facadeDiffs,
	}
	typeGraph, err := graph.Typeswap(ctx, spec)
	if err != nil {
		return classify(stageTypes, err, typesSemantic...)
	}

	analyzer, err := typeswap.New(ctx, typeswap.Options{
		Policy: r.cfg.Types.Policy,
		Pairs:  typePairs(r.cfg),
	})
	if err != nil {
		return classify(stageTypes, err, typesSemantic...)
	}
	result, err := analyzer.Analyze(ctx, typeGraph)
	if err != nil {
		return classify(stageTypes, err, typesSemantic...)
	}
	// The result is recorded before it is judged, because a blocked pairing is
	// exactly the finding a reviewer needs to read, and a refusal that discarded
	// the evidence would leave them nothing to act on.
	r.types = result
	r.report.recordTypes(result)

	if err := checkSubstitutions(result); err != nil {
		return policyError(stageTypes, err)
	}
	return nil
}

// checkSubstitutions refuses an unproved substitution and any proven rewrite
// the generation pipeline did not actually apply.
//
// The profile may prune an internal package only when the analyzer proves it is
// unreachable. A blocked pair means that proof failed. A rewrite action is also
// refused for now: publishing the relocated internal reference while reporting
// that it should have become an external one would make the report disagree with
// the generated bytes. ErrUnsupported distinguishes that missing engine feature
// from a finding about the profile.
func checkSubstitutions(result *typeswap.Result) error {
	for _, pair := range result.Pairs {
		switch pair.Action {
		case typeswap.ActionBlocked:
			return fmt.Errorf("the substitution of %s by %s is blocked, so the profile prunes a package whose equivalence was not proved:\n  %s",
				pair.Internal, pair.External, strings.Join(pair.Blockers, "\n  "))
		case typeswap.ActionRewriteReferences:
			return fmt.Errorf("%w: substituting %s with %s requires rewriting %d retained references, and generation does not yet apply those edits",
				ErrUnsupported, pair.Internal, pair.External, len(pair.Rewrites))
		}
	}
	return nil
}

// prepareUpstreamModule copies exactly the production closure into a dedicated
// scratch module for the type proof. The sparse source worktree also contains
// root-package test files; go mod tidy considers tests and would pull sibling
// packages that are deliberately outside the production closure.
func (r *run) prepareUpstreamModule(ctx context.Context) (string, error) {
	if err := ctx.Err(); err != nil {
		return "", fmt.Errorf("upstream analysis module: %w", err)
	}
	dir := filepath.Join(r.paths.Work, "types-upstream")
	if err := os.RemoveAll(dir); err != nil {
		return "", fmt.Errorf("upstream analysis module: %w", err)
	}
	if err := os.MkdirAll(dir, 0o750); err != nil {
		return "", fmt.Errorf("upstream analysis module: %w", err)
	}

	sourceRoot, err := os.OpenRoot(r.paths.PreWorktree)
	if err != nil {
		return "", fmt.Errorf("upstream analysis source: %w", err)
	}
	defer sourceRoot.Close()
	moduleRoot, err := os.OpenRoot(dir)
	if err != nil {
		return "", fmt.Errorf("upstream analysis destination: %w", err)
	}
	defer moduleRoot.Close()

	for _, file := range r.pre.Report.Closure.Report.Exact.Files {
		if err := ctx.Err(); err != nil {
			return "", fmt.Errorf("upstream analysis module: %w", err)
		}
		if strings.HasSuffix(file, "_test.go") {
			continue
		}
		if err := config.ValidateRelPath(file); err != nil {
			return "", fmt.Errorf("upstream analysis path %q: %w", file, err)
		}
		name := filepath.FromSlash(file)
		info, err := sourceRoot.Lstat(name)
		if err != nil {
			return "", fmt.Errorf("upstream analysis inspect %s: %w", file, err)
		}
		if !info.Mode().IsRegular() {
			return "", fmt.Errorf("upstream analysis inspect %s: unsupported mode %v", file, info.Mode())
		}
		contents, err := sourceRoot.ReadFile(name)
		if err != nil {
			return "", fmt.Errorf("upstream analysis read %s: %w", file, err)
		}
		if parent := filepath.Dir(name); parent != "." {
			if err := moduleRoot.MkdirAll(parent, 0o750); err != nil {
				return "", fmt.Errorf("upstream analysis directory %s: %w", file, err)
			}
		}
		mode := info.Mode().Perm()
		if err := moduleRoot.WriteFile(name, contents, mode); err != nil {
			return "", fmt.Errorf("upstream analysis write %s: %w", file, err)
		}
		// WriteFile's permission is masked by the process umask. Set it again so
		// the analysis tree represents the source mode rather than the host.
		if err := moduleRoot.Chmod(name, mode); err != nil {
			return "", fmt.Errorf("upstream analysis mode %s: %w", file, err)
		}
	}
	return dir, nil
}

// installUpstreamModule replaces the source tree's own module metadata with a
// generated provisional module.
//
// The source go.mod cannot be used as it stands. It requires every staging
// module at a placeholder version and replaces each one with a relative
// directory, and those directories are not in a sparse work tree that only
// materialized the profile's package closure, so a load would fail on the
// replacement rather than on anything about the code.
//
// What replaces it keeps the one thing that matters and drops the one thing that
// does not. The module path stays the upstream one, because that is what makes
// every package in the tree keep the import path the profile names. The staging
// replacements go, so k8s.io/api resolves to the published module at the version
// this run pinned, which is the same module the generated module will depend on
// and therefore the same type identity a consumer will see.
func (r *run) installUpstreamModule(ctx context.Context, dir string) error {
	requirements, err := modgen.RequirementsFor(r.root, r.staging)
	if err != nil {
		return fmt.Errorf("upstream module: %w", err)
	}
	goMod, err := modgen.Generate(modgen.Options{
		ModulePath: r.root.Path,
		Go:         r.root.Go,
		Godebug:    r.root.Godebug,
		Require:    requirements,
	})
	if err != nil {
		return fmt.Errorf("upstream module: %w", err)
	}

	// The source tree's metadata is removed rather than overwritten. A go.sum
	// left behind would carry checksums for the placeholder staging versions
	// this module no longer requires, and tidying would then be reconciling the
	// generated requirements against a record of a module that no longer exists.
	for _, name := range []string{"go.mod", "go.sum"} {
		if err := os.Remove(filepath.Join(dir, name)); err != nil && !errors.Is(err, fs.ErrNotExist) {
			return fmt.Errorf("upstream module: %w", err)
		}
	}
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), goMod, 0o600); err != nil {
		return fmt.Errorf("upstream module: %w", err)
	}

	runner, err := r.opts.Go.WithDir(dir)
	if err != nil {
		return fmt.Errorf("upstream module: %w", err)
	}
	// Tidying here writes rather than diffs. This module is scratch: it exists
	// to be loaded once and thrown away, and its requirements are the generated
	// ones plus whatever the unpruned closure imports that the pruned one does
	// not. That difference is expected rather than a drift to refuse, which is
	// why the tidy-diff gate belongs to the post-prune module instead.
	if err := runner.Tidy(ctx, gocli.TidyOptions{}); err != nil {
		return fmt.Errorf("upstream module: %w", err)
	}
	return nil
}

// loadUpstreamGraph type checks the upstream source tree.
//
// The pattern is the whole tree rather than the profile's roots. Both sides of
// every pairing have to be present, and so does every package that could still
// hold a use of the internal side; naming them individually is a list that goes
// stale silently, and a package missing from the load would be read as a package
// with no uses.
func (r *run) loadUpstreamGraph(ctx context.Context, dir string) (*modulegraph.Graph, error) {
	runner, err := r.opts.Go.WithDir(dir)
	if err != nil {
		return nil, fmt.Errorf("upstream graph: %w", err)
	}
	env, err := runner.LoaderEnv(ctx)
	if err != nil {
		return nil, fmt.Errorf("upstream graph: %w", err)
	}
	graph, err := modulegraph.Load(ctx, modulegraph.Options{
		Dir:      dir,
		Env:      env,
		Patterns: []string{"./..."},
		Redactor: runner.Redactor(),
	})
	if err != nil {
		return nil, fmt.Errorf("upstream graph: %w", err)
	}
	return graph, nil
}

// typePairs translates the profile's pairings into the analyzer's shape.
func typePairs(cfg *config.Config) []typeswap.Pair {
	pairs := make([]typeswap.Pair, len(cfg.Types.Pairs))
	for i, pair := range cfg.Types.Pairs {
		pairs[i] = typeswap.Pair{Internal: pair.Internal, External: pair.External}
	}
	return pairs
}
