// Package modgen generates the provisional root go.mod of the extracted module
// and proves the Go toolchain agrees with what it says.
//
// The generated module is not a copy of the source module. It has a different
// module path, it requires published staging module versions where the source
// required directories, and it carries no replace directives at all. What it
// does inherit is everything that changes how the code behaves rather than where
// it comes from: the language version and the godebug defaults.
//
// Generation and verification are separate steps on purpose. Generating a go.mod
// is a pure function of already resolved inputs, so it is cheap, deterministic,
// and testable without a toolchain. Verification is the expensive half that
// needs a real module directory and a real go command, and it exists because a
// go.mod that merely parses proves nothing: minimal version selection can raise
// a requirement above the version this package wrote, and a raised requirement
// is a dependency the operator never approved.
package modgen

import (
	"cmp"
	"errors"
	"fmt"
	"go/version"
	"slices"
	"strings"

	"golang.org/x/mod/modfile"
	"golang.org/x/mod/module"
	"golang.org/x/mod/semver"

	"github.com/enj/soapbox/tools/internal/buildinfo"
	"github.com/enj/soapbox/tools/internal/gomodmap"
)

// Options describes the module to generate.
type Options struct {
	// ModulePath is the generated module's path, such as
	// monis.app/kk/rbac_authorizer.
	ModulePath string
	// Go is the language version, inherited from the source module so the
	// extracted code is compiled under the same language semantics upstream
	// compiled it under.
	Go string
	// Toolchain is the exact patch release the generated module pins. Empty
	// means the engine's own pin, and any other value is refused: the toolchain
	// that formats the output and the toolchain the output names have to be the
	// same one, or generated bytes stop being reproducible. It is written only
	// when the go directive does not already imply it, which is what the go
	// command itself would leave behind.
	Toolchain string
	// Godebug are the source module's godebug defaults, inherited for the same
	// reason as Go. A build that honours different godebug settings than upstream
	// is a behaviour change no test of the extracted code would catch.
	Godebug []gomodmap.Godebug
	// Require lists every requirement, staging and external, at an exact
	// version.
	Require []gomodmap.Requirement
}

// RequirementsFor combines the source module's external requirements with the
// resolved staging versions.
//
// The staging modules are a subset on purpose. Resolving one costs a proxy round
// trip, and a generated module needs only those its extracted packages can
// reach, so the caller resolves what it needs and passes exactly that. A
// resolved module the source does not stage, or one passed twice, is refused
// rather than absorbed: both mean the caller and the source commit disagree
// about what the staging layout is.
//
// External requirements are copied whole instead, because they are already exact
// versions that cost nothing to carry and tidying removes the unused ones.
//
// Directness is the source module's marking, which is a starting point rather
// than an answer. The generated module contains a fraction of the source's
// packages, so tidying recomputes it, and Verify reports what it changed instead
// of promising the source's marking survived.
func RequirementsFor(root *gomodmap.RootModule, staging []gomodmap.ModuleVersion) ([]gomodmap.Requirement, error) {
	if root == nil {
		return nil, errors.New("module requirements: a parsed source module is required")
	}
	requirements := make([]gomodmap.Requirement, 0, len(root.External)+len(staging))
	requirements = append(requirements, root.External...)

	seen := make(map[string]bool, len(staging))
	for _, resolved := range staging {
		source, ok := root.StagingModuleOf(resolved.Path)
		if !ok {
			return nil, fmt.Errorf("module requirements: %s is not a staging module of %s", resolved.Path, root.Path)
		}
		if seen[resolved.Path] {
			return nil, fmt.Errorf("module requirements: staging module %s is resolved twice", resolved.Path)
		}
		seen[resolved.Path] = true
		requirements = append(requirements, gomodmap.Requirement{
			Path:     resolved.Path,
			Version:  resolved.Version,
			Indirect: source.Indirect,
		})
	}
	slices.SortFunc(requirements, func(a, b gomodmap.Requirement) int { return cmp.Compare(a.Path, b.Path) })
	return requirements, nil
}

// Generate renders the provisional go.mod.
//
// Every version has to be exact. A requirement written as a query such as
// "latest" would resolve to whatever the proxy served at the moment of the run,
// which is the one thing a reproducible extraction cannot contain, so a version
// that is not already a canonical semantic version is refused here rather than
// discovered later as an unexplained difference between two runs.
func Generate(opts Options) ([]byte, error) {
	toolchain, err := opts.resolveToolchain()
	if err != nil {
		return nil, err
	}
	if err := module.CheckPath(opts.ModulePath); err != nil {
		return nil, fmt.Errorf("generated go.mod: module path: %w", err)
	}
	if err := checkGoVersion(opts.Go); err != nil {
		return nil, fmt.Errorf("generated go.mod: go directive: %w", err)
	}
	if err := checkToolchainCovers(toolchain, opts.Go); err != nil {
		return nil, fmt.Errorf("generated go.mod: %w", err)
	}
	requirements, err := checkRequirements(opts.Require)
	if err != nil {
		return nil, err
	}
	godebug, err := checkGodebug(opts.Godebug)
	if err != nil {
		return nil, err
	}

	file := new(modfile.File)
	if err := file.AddModuleStmt(opts.ModulePath); err != nil {
		return nil, fmt.Errorf("generated go.mod: module directive: %w", err)
	}
	if err := file.AddGoStmt(opts.Go); err != nil {
		return nil, fmt.Errorf("generated go.mod: go directive: %w", err)
	}
	// A toolchain the go directive already implies is left out rather than
	// written and then removed by the first tidy. See toolchainIsImplied: the
	// engine pins one exact release, so a source module whose own go directive
	// names that same release is not an edge case but the shape upstream reaches
	// every time it moves onto the pinned patch release.
	if !toolchainIsImplied(toolchain, opts.Go) {
		if err := file.AddToolchainStmt(toolchain); err != nil {
			return nil, fmt.Errorf("generated go.mod: toolchain directive: %w", err)
		}
	}
	for _, directive := range godebug {
		if err := file.AddGodebug(directive.Key, directive.Value); err != nil {
			return nil, fmt.Errorf("generated go.mod: godebug %s: %w", directive.Key, err)
		}
	}

	// SetRequire sorts the blocks it writes, so the rendered order does not
	// depend on the order the requirements arrived in.
	required := make([]*modfile.Require, len(requirements))
	for i, requirement := range requirements {
		required[i] = &modfile.Require{
			Mod:      module.Version{Path: requirement.Path, Version: requirement.Version},
			Indirect: requirement.Indirect,
		}
	}
	file.SetRequire(required)
	file.Cleanup()

	data, err := file.Format()
	if err != nil {
		return nil, fmt.Errorf("generated go.mod: %w", err)
	}
	return data, nil
}

// resolveToolchain reports the toolchain to pin, defaulting to the engine's own.
func (o Options) resolveToolchain() (string, error) {
	if o.Toolchain == "" {
		return buildinfo.Toolchain, nil
	}
	if o.Toolchain != buildinfo.Toolchain {
		return "", fmt.Errorf("generated go.mod: toolchain %s is not the engine's pinned %s", o.Toolchain, buildinfo.Toolchain)
	}
	return o.Toolchain, nil
}

// checkRequirements validates and canonically orders the requirements.
func checkRequirements(requirements []gomodmap.Requirement) ([]gomodmap.Requirement, error) {
	if len(requirements) == 0 {
		return nil, errors.New("generated go.mod: at least one requirement is required")
	}
	ordered := slices.Clone(requirements)
	slices.SortFunc(ordered, func(a, b gomodmap.Requirement) int { return cmp.Compare(a.Path, b.Path) })
	for i, requirement := range ordered {
		if err := checkExactVersion(requirement.Version); err != nil {
			return nil, fmt.Errorf("generated go.mod: requirement %s: %w", requirement.Path, err)
		}
		// Check validates the path and the version together, which is what
		// catches a major version that disagrees with the path: k8s.io/klog/v2
		// may only be required at a v2 version, and a pin that says otherwise
		// names a module that cannot exist.
		if err := module.Check(requirement.Path, requirement.Version); err != nil {
			return nil, fmt.Errorf("generated go.mod: requirement: %w", err)
		}
		if i > 0 && ordered[i-1].Path == requirement.Path {
			return nil, fmt.Errorf("generated go.mod: module %s is required twice", requirement.Path)
		}
	}
	return ordered, nil
}

// incompatibleSuffix marks a major version 2 or later module published without
// the matching path suffix. It is the only build metadata a module version may
// carry.
const incompatibleSuffix = "+incompatible"

// checkExactVersion refuses anything the go command would have to resolve.
func checkExactVersion(version string) error {
	switch {
	case version == "":
		return errors.New("a version is required")
	case version == gomodmap.StagingVersion:
		return fmt.Errorf("version %s is the source placeholder, which names no published module", version)
	case !semver.IsValid(version):
		return fmt.Errorf("version %q is not a semantic version", version)
	}
	// Reporting other build metadata as itself is more useful than reporting it
	// as merely non canonical, which is what the check below would call it.
	if build := semver.Build(strings.TrimSuffix(version, incompatibleSuffix)); build != "" {
		return fmt.Errorf("version %q carries build metadata %q, which module versions may not", version, build)
	}
	// CanonicalVersion rather than semver.Canonical, because the latter strips
	// +incompatible and would report a legitimate version as one that needs
	// rewriting.
	if canonical := module.CanonicalVersion(version); canonical != version {
		return fmt.Errorf("version %q is not canonical, which would resolve to %q", version, canonical)
	}
	return nil
}

// checkGodebug validates and canonically orders the godebug defaults.
func checkGodebug(directives []gomodmap.Godebug) ([]gomodmap.Godebug, error) {
	ordered := slices.Clone(directives)
	slices.SortFunc(ordered, func(a, b gomodmap.Godebug) int { return cmp.Compare(a.Key, b.Key) })
	for i, directive := range ordered {
		switch {
		case directive.Key == "":
			return nil, errors.New("generated go.mod: a godebug key is required")
		case directive.Value == "":
			return nil, fmt.Errorf("generated go.mod: godebug %s has no value", directive.Key)
		}
		if i > 0 && ordered[i-1].Key == directive.Key {
			return nil, fmt.Errorf("generated go.mod: godebug %s is set twice", directive.Key)
		}
	}
	return ordered, nil
}

// checkGoVersion accepts the forms a go directive may take.
func checkGoVersion(version string) error {
	if version == "" {
		return errors.New("a version is required")
	}
	if !modfile.GoVersionRE.MatchString(version) {
		return fmt.Errorf("version %q is not a Go language version", version)
	}
	return nil
}

// checkToolchainCovers refuses a toolchain older than the language version it is
// meant to compile, which the go command rejects at load time rather than at the
// point the two were chosen.
//
// The comparison is the go command's own, not a semantic version one. Go
// releases are not semantic versions: "1.26" is a language version that sorts
// below the "1.26.0" release, and a prerelease such as "1.26rc1" sorts below
// both while being neither a valid semver core nor a valid semver prerelease of
// one. Rendering either into semver produces an invalid string that compares
// equal to everything, which would silently accept a toolchain that cannot
// build the module.
func checkToolchainCovers(toolchain, goVersion string) error {
	if !strings.HasPrefix(toolchain, toolchainPrefix) || !version.IsValid(toolchain) {
		return fmt.Errorf("toolchain %q must name a Go release", toolchain)
	}
	if version.Compare(toolchain, toolchainPrefix+goVersion) < 0 {
		return fmt.Errorf("toolchain %s is older than the go directive %s", toolchain, goVersion)
	}
	return nil
}

// toolchainPrefix is what turns a go directive's language version into the
// toolchain name that names the same release.
const toolchainPrefix = "go"

// toolchainIsImplied reports whether the go directive already selects this
// toolchain, which is when the go command drops the directive as redundant.
//
// Writing it anyway would make every generated module drift on its first tidy,
// because the file the engine wrote and the file the go command left behind
// would differ by a line the engine never got to explain. The rule is the go
// command's: a toolchain that is not newer than the go directive says nothing
// the go directive did not already say.
func toolchainIsImplied(toolchain, goVersion string) bool {
	return version.Compare(toolchain, toolchainPrefix+goVersion) <= 0
}
