package modgen_test

import (
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/buildinfo"
	"github.com/enj/soapbox/tools/internal/gomodmap"
	"github.com/enj/soapbox/tools/internal/modgen"
)

// generatedModulePath is the module the RBAC profile publishes.
const generatedModulePath = "monis.app/kk/rbac_authorizer"

// baseOptions returns options shaped like a real extraction: the language
// version and godebug defaults come from the source module, the toolchain is the
// engine's own pin, and every requirement carries an exact version.
func baseOptions() modgen.Options {
	return modgen.Options{
		ModulePath: generatedModulePath,
		Go:         "1.26.0",
		Godebug:    []gomodmap.Godebug{{Key: "default", Value: "go1.26"}},
		Require: []gomodmap.Requirement{
			{Path: "k8s.io/apimachinery", Version: "v0.36.1"},
			{Path: "k8s.io/api", Version: "v0.36.1"},
			{Path: "github.com/spf13/cobra", Version: "v1.10.1"},
			{Path: "k8s.io/klog/v2", Version: "v2.130.1", Indirect: true},
		},
	}
}

func TestGenerate(t *testing.T) {
	t.Parallel()

	data, err := modgen.Generate(baseOptions())
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	got := string(data)

	// Requirements are sorted by path regardless of the order they arrived in,
	// indirect markings are preserved, and the toolchain is the engine's pin.
	want := `module monis.app/kk/rbac_authorizer

go 1.26.0

toolchain ` + buildinfo.Toolchain + `

godebug default=go1.26

require (
	github.com/spf13/cobra v1.10.1
	k8s.io/api v0.36.1
	k8s.io/apimachinery v0.36.1
	k8s.io/klog/v2 v2.130.1 // indirect
)
`
	if got != want {
		t.Errorf("generated go.mod:\n%s\nwant:\n%s", got, want)
	}
	if strings.Contains(got, "replace") {
		t.Error("generated go.mod carries a replace directive")
	}
}

// TestGenerate_Deterministic proves the output does not depend on the order the
// requirements or godebug directives were supplied in.
func TestGenerate_Deterministic(t *testing.T) {
	t.Parallel()

	forward := baseOptions()
	forward.Godebug = []gomodmap.Godebug{
		{Key: "default", Value: "go1.26"},
		{Key: "winsymlink", Value: "0"},
	}

	reversed := baseOptions()
	reversed.Godebug = []gomodmap.Godebug{
		{Key: "winsymlink", Value: "0"},
		{Key: "default", Value: "go1.26"},
	}
	reversed.Require = []gomodmap.Requirement{
		{Path: "k8s.io/klog/v2", Version: "v2.130.1", Indirect: true},
		{Path: "github.com/spf13/cobra", Version: "v1.10.1"},
		{Path: "k8s.io/api", Version: "v0.36.1"},
		{Path: "k8s.io/apimachinery", Version: "v0.36.1"},
	}

	first, err := modgen.Generate(forward)
	if err != nil {
		t.Fatalf("generate forward: %v", err)
	}
	second, err := modgen.Generate(reversed)
	if err != nil {
		t.Fatalf("generate reversed: %v", err)
	}
	if string(first) != string(second) {
		t.Errorf("generated bytes differ:\n%s\n---\n%s", first, second)
	}
}

// TestGenerate_DoesNotMutateOptions proves generation leaves the caller's slices
// in the order they were passed, so a caller can reuse them.
func TestGenerate_DoesNotMutateOptions(t *testing.T) {
	t.Parallel()

	opts := baseOptions()
	first := opts.Require[0].Path
	if _, err := modgen.Generate(opts); err != nil {
		t.Fatalf("generate: %v", err)
	}
	if opts.Require[0].Path != first {
		t.Errorf("requirements were reordered in place: [0] is now %s, want %s", opts.Require[0].Path, first)
	}
}

// TestGenerate_OmitsImpliedToolchain proves a toolchain the go directive already
// selects is left out.
//
// The go command removes such a directive as redundant, so writing it would make
// every generated module drift on its first tidy: the file the engine wrote and
// the file the go command left behind would differ by a line the engine never
// got to explain. This is not an edge case, because the engine pins one exact
// release and upstream reaches that same release whenever it moves its own go
// directive onto the current patch.
func TestGenerate_OmitsImpliedToolchain(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name          string
		goDirective   string
		wantToolchain bool
	}{
		{
			name:          "go directive names the pinned release",
			goDirective:   strings.TrimPrefix(buildinfo.Toolchain, "go"),
			wantToolchain: false,
		},
		{
			// A language version without a patch sorts below the release that
			// carries one, so the toolchain still says something.
			name:          "go directive names only the language version",
			goDirective:   "1.26",
			wantToolchain: true,
		},
		{
			name:          "go directive names an older patch release",
			goDirective:   "1.26.0",
			wantToolchain: true,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			opts := baseOptions()
			opts.Go = test.goDirective
			data, err := modgen.Generate(opts)
			if err != nil {
				t.Fatalf("generate: %v", err)
			}
			got := strings.Contains(string(data), "toolchain "+buildinfo.Toolchain)
			if got != test.wantToolchain {
				t.Errorf("toolchain directive present = %v, want %v, in:\n%s", got, test.wantToolchain, data)
			}
		})
	}
}

func TestGenerate_Rejects(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		mutate  func(*modgen.Options)
		wantErr string
	}{
		{
			name:    "empty module path",
			mutate:  func(o *modgen.Options) { o.ModulePath = "" },
			wantErr: "module path",
		},
		{
			name:    "module path is not a module path",
			mutate:  func(o *modgen.Options) { o.ModulePath = "not a module path" },
			wantErr: "module path",
		},
		{
			name:    "missing go directive",
			mutate:  func(o *modgen.Options) { o.Go = "" },
			wantErr: "go directive: a version is required",
		},
		{
			name:    "go directive is not a version",
			mutate:  func(o *modgen.Options) { o.Go = "tip" },
			wantErr: "is not a Go language version",
		},
		{
			// The toolchain that formats the output and the toolchain the output
			// names have to be the same one.
			name:    "toolchain is not the engine pin",
			mutate:  func(o *modgen.Options) { o.Toolchain = "go1.25.0" },
			wantErr: "is not the engine's pinned",
		},
		{
			name:    "toolchain older than the go directive",
			mutate:  func(o *modgen.Options) { o.Go = "1.99.0" },
			wantErr: "older than the go directive",
		},
		{
			// A prerelease language version is a real go directive and is not a
			// semantic version. Rendering it into one yields an invalid string that
			// compares below everything, which would silently accept the pinned
			// toolchain as able to compile a language it predates.
			name:    "toolchain older than a prerelease go directive",
			mutate:  func(o *modgen.Options) { o.Go = "1.99rc1" },
			wantErr: "older than the go directive",
		},
		{
			name:    "no requirements",
			mutate:  func(o *modgen.Options) { o.Require = nil },
			wantErr: "at least one requirement is required",
		},
		{
			name: "requirement at the staging placeholder",
			mutate: func(o *modgen.Options) {
				o.Require[0].Version = gomodmap.StagingVersion
			},
			wantErr: "is the source placeholder",
		},
		{
			// A query rather than a version would resolve to whatever the proxy
			// served at the moment of the run.
			name: "requirement at a query",
			mutate: func(o *modgen.Options) {
				o.Require[0].Version = "latest"
			},
			wantErr: "is not a semantic version",
		},
		{
			name: "requirement at a non canonical version",
			mutate: func(o *modgen.Options) {
				o.Require[0].Version = "v0.36"
			},
			wantErr: "is not canonical",
		},
		{
			name: "requirement with build metadata",
			mutate: func(o *modgen.Options) {
				o.Require[0].Version = "v0.36.1+meta"
			},
			wantErr: "build metadata",
		},
		{
			name: "requirement without a version",
			mutate: func(o *modgen.Options) {
				o.Require[0].Version = ""
			},
			wantErr: "a version is required",
		},
		{
			name: "module required twice",
			mutate: func(o *modgen.Options) {
				o.Require = append(o.Require, gomodmap.Requirement{Path: "k8s.io/api", Version: "v0.36.1"})
			},
			wantErr: "is required twice",
		},
		{
			name: "godebug without a value",
			mutate: func(o *modgen.Options) {
				o.Godebug = []gomodmap.Godebug{{Key: "default"}}
			},
			wantErr: "has no value",
		},
		{
			name: "godebug set twice",
			mutate: func(o *modgen.Options) {
				o.Godebug = []gomodmap.Godebug{{Key: "default", Value: "go1.26"}, {Key: "default", Value: "go1.25"}}
			},
			wantErr: "is set twice",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			opts := baseOptions()
			test.mutate(&opts)
			_, err := modgen.Generate(opts)
			if err == nil {
				t.Fatalf("generate: got nil error, want %q", test.wantErr)
			}
			if !strings.Contains(err.Error(), test.wantErr) {
				t.Errorf("generate: error = %v, want it to contain %q", err, test.wantErr)
			}
		})
	}
}

// TestGenerate_AcceptsIncompatible proves the one build metadata suffix the
// module system does allow is not mistaken for a version that needs rewriting.
// Kubernetes really does require modules this way, so rejecting it would fail
// the extraction outright.
func TestGenerate_AcceptsIncompatible(t *testing.T) {
	t.Parallel()

	opts := baseOptions()
	opts.Require = append(opts.Require, gomodmap.Requirement{
		Path:    "github.com/docker/docker",
		Version: "v20.10.27+incompatible",
	})
	data, err := modgen.Generate(opts)
	if err != nil {
		t.Fatalf("generate: %v", err)
	}
	if !strings.Contains(string(data), "github.com/docker/docker v20.10.27+incompatible") {
		t.Errorf("generated go.mod dropped the +incompatible requirement:\n%s", data)
	}
}

// TestGenerate_RejectsMajorVersionMismatch proves a pin whose major version
// disagrees with its module path is refused, because it names a module that
// cannot exist.
func TestGenerate_RejectsMajorVersionMismatch(t *testing.T) {
	t.Parallel()

	opts := baseOptions()
	for i := range opts.Require {
		if opts.Require[i].Path == "k8s.io/klog/v2" {
			opts.Require[i].Version = "v1.130.1"
		}
	}
	_, err := modgen.Generate(opts)
	if err == nil {
		t.Fatal("generate: got nil error, want a major version mismatch")
	}
	if !strings.Contains(err.Error(), "k8s.io/klog/v2") {
		t.Errorf("generate: error = %v, want it to name the module", err)
	}
}

func TestRequirementsFor(t *testing.T) {
	t.Parallel()

	root, err := gomodmap.ParseRootModule("go.mod", []byte(`module k8s.io/kubernetes

go 1.26.0

require (
	github.com/spf13/cobra v1.10.1
	k8s.io/api v0.0.0
	k8s.io/apimachinery v0.0.0
	k8s.io/klog/v2 v2.130.1 // indirect
)

replace (
	k8s.io/api => ./staging/src/k8s.io/api
	k8s.io/apimachinery => ./staging/src/k8s.io/apimachinery
)
`))
	if err != nil {
		t.Fatalf("parse root module: %v", err)
	}

	// Only the reached staging module is resolved, which is the normal case: an
	// extraction reaches a handful of the staging modules Kubernetes publishes.
	requirements, err := modgen.RequirementsFor(root, []gomodmap.ModuleVersion{
		{Path: "k8s.io/api", Version: "v0.36.1"},
	})
	if err != nil {
		t.Fatalf("requirements: %v", err)
	}

	want := []gomodmap.Requirement{
		{Path: "github.com/spf13/cobra", Version: "v1.10.1"},
		{Path: "k8s.io/api", Version: "v0.36.1"},
		{Path: "k8s.io/klog/v2", Version: "v2.130.1", Indirect: true},
	}
	if len(requirements) != len(want) {
		t.Fatalf("requirements = %v, want %v", requirements, want)
	}
	for i, requirement := range want {
		if requirements[i] != requirement {
			t.Errorf("requirements[%d] = %v, want %v", i, requirements[i], requirement)
		}
	}
}

// TestRequirementsFor_PreservesDirectness proves an indirect staging module
// stays indirect, because the extracted module requires it for the same reason
// upstream did.
func TestRequirementsFor_PreservesDirectness(t *testing.T) {
	t.Parallel()

	root, err := gomodmap.ParseRootModule("go.mod", []byte(`module k8s.io/kubernetes

go 1.26.0

require k8s.io/api v0.0.0 // indirect

replace k8s.io/api => ./staging/src/k8s.io/api
`))
	if err != nil {
		t.Fatalf("parse root module: %v", err)
	}

	requirements, err := modgen.RequirementsFor(root, []gomodmap.ModuleVersion{
		{Path: "k8s.io/api", Version: "v0.36.1"},
	})
	if err != nil {
		t.Fatalf("requirements: %v", err)
	}
	if len(requirements) != 1 {
		t.Fatalf("requirements = %v, want 1", requirements)
	}
	if !requirements[0].Indirect {
		t.Error("staging requirement lost its indirect marking")
	}
}

// replaceOnlyRoot parses a source module that stages a module without requiring
// it, which is the shape Kubernetes really has for sample-cli-plugin and
// sample-controller: replaced so the tree publishes them, imported by nothing in
// the root module, so no requirement and no resolved version.
func replaceOnlyRoot(t *testing.T) *gomodmap.RootModule {
	t.Helper()
	root, err := gomodmap.ParseRootModule("go.mod", []byte(`module k8s.io/kubernetes

go 1.26.0

require k8s.io/api v0.0.0

replace (
	k8s.io/api => ./staging/src/k8s.io/api
	k8s.io/sample-controller => ./staging/src/k8s.io/sample-controller
)
`))
	if err != nil {
		t.Fatalf("parse root module: %v", err)
	}
	return root
}

func TestRequirementsFor_Rejects(t *testing.T) {
	t.Parallel()
	root, err := gomodmap.ParseRootModule("go.mod", []byte(`module k8s.io/kubernetes

go 1.26.0

require k8s.io/api v0.0.0

replace k8s.io/api => ./staging/src/k8s.io/api
`))
	if err != nil {
		t.Fatalf("parse root module: %v", err)
	}

	tests := []struct {
		name    string
		root    *gomodmap.RootModule
		staging []gomodmap.ModuleVersion
		wantErr string
	}{
		{
			name:    "no parsed source module",
			staging: []gomodmap.ModuleVersion{{Path: "k8s.io/api", Version: "v0.36.1"}},
			wantErr: "a parsed source module is required",
		},
		{
			// Resolving a module the source does not stage would pin a published
			// module the extraction never read.
			name:    "resolved module is not a staging module",
			root:    root,
			staging: []gomodmap.ModuleVersion{{Path: "k8s.io/apiserver", Version: "v0.36.1"}},
			wantErr: "is not a staging module of k8s.io/kubernetes",
		},
		{
			name: "staging module resolved twice",
			root: root,
			staging: []gomodmap.ModuleVersion{
				{Path: "k8s.io/api", Version: "v0.36.1"},
				{Path: "k8s.io/api", Version: "v0.36.2"},
			},
			wantErr: "is resolved twice",
		},
		{
			// sample-controller is the real shape: staged so the tree publishes
			// it, required by nothing, so upstream's own build never resolved a
			// version for it. Requiring it here would have the generated module
			// depend on code the source commit was never built against.
			name:    "staging module is replaced but not required",
			root:    replaceOnlyRoot(t),
			staging: []gomodmap.ModuleVersion{{Path: "k8s.io/sample-controller", Version: "v0.36.1"}},
			wantErr: "not required by it",
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			_, err := modgen.RequirementsFor(test.root, test.staging)
			if err == nil {
				t.Fatalf("requirements: got nil error, want %q", test.wantErr)
			}
			if !strings.Contains(err.Error(), test.wantErr) {
				t.Errorf("requirements: error = %v, want it to contain %q", err, test.wantErr)
			}
		})
	}
}

// TestGenerate_FromParsedSource proves the two halves compose: a parsed source
// module and a resolved staging version produce a module file with no
// replacements and no placeholder versions left in it.
func TestGenerate_FromParsedSource(t *testing.T) {
	t.Parallel()

	root, err := gomodmap.ParseRootModule("go.mod", []byte(`module k8s.io/kubernetes

go 1.26.0

godebug default=go1.26

require (
	k8s.io/api v0.0.0
	k8s.io/klog/v2 v2.130.1 // indirect
)

replace k8s.io/api => ./staging/src/k8s.io/api
`))
	if err != nil {
		t.Fatalf("parse root module: %v", err)
	}
	requirements, err := modgen.RequirementsFor(root, []gomodmap.ModuleVersion{
		{Path: "k8s.io/api", Version: "v0.36.1"},
	})
	if err != nil {
		t.Fatalf("requirements: %v", err)
	}

	data, err := modgen.Generate(modgen.Options{
		ModulePath: generatedModulePath,
		Go:         root.Go,
		Godebug:    root.Godebug,
		Require:    requirements,
	})
	if err != nil {
		t.Fatalf("generate: %v", err)
	}

	got := string(data)
	for _, unwanted := range []string{"replace", gomodmap.StagingVersion, "k8s.io/kubernetes"} {
		if strings.Contains(got, unwanted) {
			t.Errorf("generated go.mod contains %q:\n%s", unwanted, got)
		}
	}
	for _, wanted := range []string{"k8s.io/api v0.36.1", "godebug default=go1.26", "go 1.26.0"} {
		if !strings.Contains(got, wanted) {
			t.Errorf("generated go.mod is missing %q:\n%s", wanted, got)
		}
	}
}
