/*
Copyright 2014 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by soapbox. DO NOT EDIT.
// This module-local compatibility declaration is intentionally not type-compatible with k8s.io/apiserver.
// Upstream repository: https://github.com/kubernetes/kubernetes.git
// Upstream path: staging/src/k8s.io/apiserver/pkg/authentication/user/user.go
// Upstream commit: 24e2b02af5543d7910c2bb074c7264df5a8f0467

package user

// Info describes an authenticated user for the module-local authorization API.
type Info interface {
	GetName() string
	GetUID() string
	GetGroups() []string
	GetExtra() map[string][]string
}

// DefaultInfo is the module-local user information record.
type DefaultInfo struct {
	Name string
	UID string
	Groups []string
	Extra map[string][]string
}

func (i *DefaultInfo) GetName() string { return i.Name }
func (i *DefaultInfo) GetUID() string { return i.UID }
func (i *DefaultInfo) GetGroups() []string { return i.Groups }
func (i *DefaultInfo) GetExtra() map[string][]string { return i.Extra }

const SystemPrivilegedGroup = "system:masters"
