// Command soapbox runs the pinned Soapbox engine for this repository.
//
// Generated by soapbox setup. The engine release this builds against is pinned
// in the go.mod beside it; nothing here changes when the engine does.
package main

import (
	"context"
	"os"
	"os/signal"
	"syscall"

	soapbox "github.com/enj/soapbox/tools"
)

func main() {
	os.Exit(run())
}

// run keeps the signal handler teardown ahead of the process exit.
func run() int {
	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	return soapbox.Main(ctx, os.Args[1:])
}
