package typeswap_test

import (
	"context"
	"slices"
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/typeswap"
)

const (
	internalRBAC   = "k8s.io/kubernetes/pkg/apis/rbac"
	internalRBACV1 = "k8s.io/kubernetes/pkg/apis/rbac/v1"
	externalRBAC   = "k8s.io/api/rbac/v1"
	validationPkg  = "k8s.io/kubernetes/pkg/registry/rbac/validation"
	conversionPkg  = "k8s.io/apimachinery/pkg/conversion"
)

// rbacFiles is shaped like the real RBAC extraction: an internal API package
// that registers itself into a scheme, a published package with identical
// types, a versioned package holding the generated conversions and the
// generator directives, and retained code that was already written against the
// published package.
//
// The last part is the whole point. Nothing retained names the internal
// package, so the correct action is to prune it rather than to rewrite
// anything, and the analysis has to reach that conclusion from the code rather
// than from configuration asserting it.
var rbacFiles = map[string]string{
	conversionPkg + "/converter.go": `package conversion

// Scope is the conversion context generated functions receive.
type Scope interface {
	Convert(src, dest any) error
}
`,

	externalRBAC + "/types.go": `// +groupName=rbac.authorization.k8s.io

package v1

// PolicyRule holds information that describes a policy rule.
type PolicyRule struct {
	Verbs           []string ` + "`json:\"verbs\" protobuf:\"bytes,1,rep,name=verbs\"`" + `
	APIGroups       []string ` + "`json:\"apiGroups,omitempty\" protobuf:\"bytes,2,rep,name=apiGroups\"`" + `
	Resources       []string ` + "`json:\"resources,omitempty\" protobuf:\"bytes,3,rep,name=resources\"`" + `
	ResourceNames   []string ` + "`json:\"resourceNames,omitempty\" protobuf:\"bytes,4,rep,name=resourceNames\"`" + `
	NonResourceURLs []string ` + "`json:\"nonResourceURLs,omitempty\" protobuf:\"bytes,5,rep,name=nonResourceURLs\"`" + `
}

// Subject contains a reference to the object or user identities a binding
// applies to.
type Subject struct {
	Kind      string ` + "`json:\"kind\" protobuf:\"bytes,1,opt,name=kind\"`" + `
	APIGroup  string ` + "`json:\"apiGroup,omitempty\" protobuf:\"bytes,2,opt,name=apiGroup\"`" + `
	Name      string ` + "`json:\"name\" protobuf:\"bytes,3,opt,name=name\"`" + `
	Namespace string ` + "`json:\"namespace,omitempty\" protobuf:\"bytes,4,opt,name=namespace\"`" + `
}

// Role is a namespaced set of rules.
type Role struct {
	Name  string       ` + "`json:\"name\" protobuf:\"bytes,1,opt,name=name\"`" + `
	Rules []PolicyRule ` + "`json:\"rules\" protobuf:\"bytes,2,rep,name=rules\"`" + `
}

// String renders the role for logging.
func (r *Role) String() string { return r.Name }
`,

	internalRBAC + "/types.go": `// +k8s:deepcopy-gen=package
// +groupName=rbac.authorization.k8s.io

package rbac

// PolicyRule holds information that describes a policy rule.
type PolicyRule struct {
	Verbs           []string ` + "`json:\"verbs\" protobuf:\"bytes,1,rep,name=verbs\"`" + `
	APIGroups       []string ` + "`json:\"apiGroups,omitempty\" protobuf:\"bytes,2,rep,name=apiGroups\"`" + `
	Resources       []string ` + "`json:\"resources,omitempty\" protobuf:\"bytes,3,rep,name=resources\"`" + `
	ResourceNames   []string ` + "`json:\"resourceNames,omitempty\" protobuf:\"bytes,4,rep,name=resourceNames\"`" + `
	NonResourceURLs []string ` + "`json:\"nonResourceURLs,omitempty\" protobuf:\"bytes,5,rep,name=nonResourceURLs\"`" + `
}

// Subject contains a reference to the object or user identities a binding
// applies to.
type Subject struct {
	Kind      string ` + "`json:\"kind\" protobuf:\"bytes,1,opt,name=kind\"`" + `
	APIGroup  string ` + "`json:\"apiGroup,omitempty\" protobuf:\"bytes,2,opt,name=apiGroup\"`" + `
	Name      string ` + "`json:\"name\" protobuf:\"bytes,3,opt,name=name\"`" + `
	Namespace string ` + "`json:\"namespace,omitempty\" protobuf:\"bytes,4,opt,name=namespace\"`" + `
}

// Role is a namespaced set of rules.
type Role struct {
	Name  string       ` + "`json:\"name\" protobuf:\"bytes,1,opt,name=name\"`" + `
	Rules []PolicyRule ` + "`json:\"rules\" protobuf:\"bytes,2,rep,name=rules\"`" + `
}

// String renders the role for logging.
func (r *Role) String() string { return r.Name }
`,

	internalRBAC + "/register.go": `package rbac

// SchemeBuilder collects the functions that add these types to a scheme.
var SchemeBuilder = []func() error{}

// AddToScheme registers the internal types.
var AddToScheme = func() error { return nil }

func init() {
	SchemeBuilder = append(SchemeBuilder, AddToScheme)
}
`,

	internalRBACV1 + "/doc.go": `// +k8s:conversion-gen=k8s.io/kubernetes/pkg/apis/rbac
// +k8s:conversion-gen-external-types=k8s.io/api/rbac/v1
// +k8s:defaulter-gen=TypeMeta
// +groupName=rbac.authorization.k8s.io

// Package v1 holds the conversions between the internal and published RBAC
// types.
package v1
`,

	internalRBACV1 + "/zz_generated.conversion.go": `// Code generated by conversion-gen. DO NOT EDIT.

package v1

import (
	unsafe "unsafe"

	v1 "k8s.io/api/rbac/v1"
	conversion "k8s.io/apimachinery/pkg/conversion"
	rbac "k8s.io/kubernetes/pkg/apis/rbac"
)

func Convert_v1_PolicyRule_To_rbac_PolicyRule(in *v1.PolicyRule, out *rbac.PolicyRule, s conversion.Scope) error {
	out.Verbs = *(*[]string)(unsafe.Pointer(&in.Verbs))
	out.APIGroups = *(*[]string)(unsafe.Pointer(&in.APIGroups))
	out.Resources = *(*[]string)(unsafe.Pointer(&in.Resources))
	out.ResourceNames = *(*[]string)(unsafe.Pointer(&in.ResourceNames))
	out.NonResourceURLs = *(*[]string)(unsafe.Pointer(&in.NonResourceURLs))
	return nil
}

func Convert_v1_Subject_To_rbac_Subject(in *v1.Subject, out *rbac.Subject, s conversion.Scope) error {
	out.Kind = in.Kind
	out.APIGroup = in.APIGroup
	out.Name = in.Name
	out.Namespace = in.Namespace
	return nil
}

func Convert_v1_Role_To_rbac_Role(in *v1.Role, out *rbac.Role, s conversion.Scope) error {
	out.Name = in.Name
	out.Rules = *(*[]rbac.PolicyRule)(unsafe.Pointer(&in.Rules))
	return nil
}
`,

	validationPkg + "/rule.go": `package validation

import (
	rbacv1 "k8s.io/api/rbac/v1"
)

// AuthorizationRuleResolver resolves the rules that apply to a subject.
type AuthorizationRuleResolver interface {
	RulesFor(namespace string) ([]rbacv1.PolicyRule, error)
}

// RuleAllows reports whether any rule permits the verb.
func RuleAllows(rules []rbacv1.PolicyRule, verb string) bool {
	for _, rule := range rules {
		for _, candidate := range rule.Verbs {
			if candidate == verb || candidate == "*" {
				return true
			}
		}
	}
	return false
}
`,
}

// rbacPair is the pairing soapbox.yaml configures.
var rbacPair = typeswap.Pair{Internal: internalRBAC, External: externalRBAC}

// rbacRetained is the package set that survives pruning: the retained helper
// packages and the published API, but not the internal one.
var rbacRetained = []string{validationPkg, internalRBACV1, externalRBAC, conversionPkg}

// rbacPruned are the files soapbox.yaml removes. The conversion file goes
// while its package survives for doc.go and the retained helpers, which is why
// the graph tracks pruning per file rather than per package.
var rbacPruned = []string{internalRBACV1 + "/zz_generated.conversion.go"}

// rbacGraph builds the pre-prune graph with the retained set and pruned files
// the profile declares.
func rbacGraph(f *fixture) *typeswap.Graph {
	graph := f.graph(rbacRetained...)
	graph.PrunedFiles = rbacPruned
	return graph
}

func analyzeRBAC(t *testing.T) (*typeswap.Result, *fixture) {
	t.Helper()
	ctx := context.Background()

	f := newFixture(t, rbacFiles)
	analyzer, err := typeswap.New(ctx, typeswap.Options{
		Policy: typeswap.PolicyPreferExternal,
		Pairs:  []typeswap.Pair{rbacPair},
	})
	if err != nil {
		t.Fatalf("new analyzer: %v", err)
	}
	result, err := analyzer.Analyze(ctx, rbacGraph(f))
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}
	return result, f
}

// TestRBACPrunesInternalWithoutRewriting is the outcome the design calls for:
// the internal package is pruned, no retained type is rewritten, and the
// analysis reaches that from the code.
func TestRBACPrunesInternalWithoutRewriting(t *testing.T) {
	t.Parallel()

	result, _ := analyzeRBAC(t)
	report, ok := result.Pair(internalRBAC)
	if !ok {
		t.Fatalf("result has no pair for %s", internalRBAC)
	}

	if len(report.Blockers) > 0 {
		t.Fatalf("pairing is blocked by %v", report.Blockers)
	}
	if report.Action != typeswap.ActionPruneInternal {
		t.Errorf("action = %q, want %q", report.Action, typeswap.ActionPruneInternal)
	}
	if len(report.Rewrites) != 0 {
		t.Errorf("rewrites = %v, want none", report.Rewrites)
	}
	if got := report.FailedAnalyses(); len(got) != 0 {
		t.Errorf("failed analyses = %v, want none", got)
	}

	// The conclusion rests on retained code already using the published
	// package, so that observation has to be recorded rather than assumed.
	if !slices.Contains(report.ExternalAlreadyUsed, validationPkg) {
		t.Errorf("externalAlreadyUsed = %v, want it to include %s", report.ExternalAlreadyUsed, validationPkg)
	}
}

// TestRBACRecordsSchemeBehaviorChanges checks that pruning's real effects are
// written down. They are harmless here, which is exactly why an analysis that
// stopped reporting them would go unnoticed.
func TestRBACRecordsSchemeBehaviorChanges(t *testing.T) {
	t.Parallel()

	result, _ := analyzeRBAC(t)
	report, _ := result.Pair(internalRBAC)

	if len(report.ObservableChanges()) != 0 {
		t.Errorf("observable changes = %v, want none for a pruned package nothing retains", report.ObservableChanges())
	}

	summary := strings.Join(report.ChangeSummary(), "\n")
	for _, want := range []string{
		internalRBAC + ".SchemeBuilder",
		internalRBAC + ".AddToScheme",
		internalRBAC + ".init",
	} {
		if !strings.Contains(summary, want) {
			t.Errorf("behavior changes do not mention %q:\n%s", want, summary)
		}
	}

	// The retained doc.go still carries +k8s:conversion-gen naming the pruned
	// package. That dangling directive is a real change and must be listed so
	// the rewrite phase strips it and provenance records it.
	if !strings.Contains(summary, typeswap.MarkerConversionGen) {
		t.Errorf("behavior changes do not list the dangling generator directive:\n%s", summary)
	}
}

// TestRBACProofsAllHold checks each of the five analyses individually, so a
// proof that silently stopped running is visible rather than absorbed into an
// overall pass.
func TestRBACProofsAllHold(t *testing.T) {
	t.Parallel()

	result, _ := analyzeRBAC(t)
	report, _ := result.Pair(internalRBAC)

	tests := []struct {
		analysis string
		mentions string
	}{
		{typeswap.AnalysisMarkers, "+k8s:conversion-gen=" + internalRBAC},
		{typeswap.AnalysisConversions, "Convert_v1_Role_To_rbac_Role is field preserving"},
		{typeswap.AnalysisMethodSets, "equivalent method sets"},
		{typeswap.AnalysisFieldIdentity, "match recursively on field names"},
		{typeswap.AnalysisGlobalEffects, "unobservable through the generated API"},
	}
	for _, test := range tests {
		t.Run(test.analysis, func(t *testing.T) {
			analysis, ok := report.Analysis(test.analysis)
			if !ok {
				t.Fatalf("report has no %s analysis", test.analysis)
			}
			if !analysis.Passed {
				t.Fatalf("%s failed: %v", test.analysis, analysis.Blockers)
			}
			evidence := strings.Join(analysis.Evidence, "\n")
			if !strings.Contains(evidence, test.mentions) {
				t.Errorf("%s evidence does not mention %q:\n%s", test.analysis, test.mentions, evidence)
			}
		})
	}
}

// TestPublicAPIDifferenceBlocksPruning is the pre-prune and post-prune
// comparison the design requires.
//
// The comparison itself is the facade's: it owns what the generated public API
// is and already renders and diffs its own manifest, so this package takes the
// rendered result rather than building a second manifest and a second differ
// that could disagree with the first. What it does own is the consequence. The
// whole argument for pruning is that the public API does not notice, so a
// reported difference blocks the substitution no matter which proof passed.
func TestPublicAPIDifferenceBlocksPruning(t *testing.T) {
	t.Parallel()
	ctx := context.Background()

	f := newFixture(t, rbacFiles)
	analyzer, err := typeswap.New(ctx, typeswap.Options{
		Policy: typeswap.PolicyPreferExternal,
		Pairs:  []typeswap.Pair{rbacPair},
	})
	if err != nil {
		t.Fatalf("new analyzer: %v", err)
	}

	// With no differences the pairing prunes, which is the RBAC outcome.
	clean, err := analyzer.Analyze(ctx, rbacGraph(f))
	if err != nil {
		t.Fatalf("analyze: %v", err)
	}
	if report, _ := clean.Pair(internalRBAC); report.Action != typeswap.ActionPruneInternal {
		t.Fatalf("action = %q, want %q", report.Action, typeswap.ActionPruneInternal)
	}

	// One difference is enough to refuse, because the module ships under an
	// immutable tag and a consumer's build breaking is not something the five
	// proofs can outvote.
	graph := rbacGraph(f)
	graph.PublicAPIDifferences = []string{"changed RuleAllows: func(...) bool became func(..., bool) bool"}
	blocked, err := analyzer.Analyze(ctx, graph)
	if err != nil {
		t.Fatalf("analyze with a difference: %v", err)
	}
	report, _ := blocked.Pair(internalRBAC)
	if report.Action != typeswap.ActionBlocked {
		t.Fatalf("action = %q, want %q", report.Action, typeswap.ActionBlocked)
	}
	if !equalStrings(report.PublicAPIDifferences, graph.PublicAPIDifferences) {
		t.Errorf("publicApiDifferences = %v, want %v", report.PublicAPIDifferences, graph.PublicAPIDifferences)
	}
	blockers := strings.Join(report.Blockers, "\n")
	if !strings.Contains(blockers, "pruning changes the generated public API") {
		t.Errorf("blockers do not explain the API change:\n%s", blockers)
	}
}

// equalStrings compares two string slices, treating nil and empty as equal.
func equalStrings(got, want []string) bool {
	if len(got) != len(want) {
		return false
	}
	for i := range got {
		if got[i] != want[i] {
			return false
		}
	}
	return true
}
