package closure

import (
	"errors"
	"fmt"
	"path"
	"slices"
	"strings"
)

// Options configures one closure build.
//
// The struct is deliberately independent of internal/config. Closure is the
// lower layer: config already validates and normalizes a profile, and a config
// import here would stop config from ever reusing this package. A caller
// translates a profile into Options at the boundary, which also keeps the
// engine able to compute a closure for a tree that no profile describes yet.
type Options struct {
	// Root is the already materialized upstream worktree. This package never
	// clones or checks out anything; it reads, prunes, and plans copies inside
	// the tree it is handed.
	Root string
	// ImportPrefix is the source module path, for example k8s.io/kubernetes.
	// Only imports rooted here are followed; everything else is recorded as an
	// external boundary import and left to the dependency policy.
	ImportPrefix string
	// Roots are repository relative package directories that seed the closure.
	Roots []string
	// Recursive expands every configured root to each subdirectory that holds
	// Go files. Discovered packages are never expanded: they enter the closure
	// at the exact import path that referenced them, so a sibling subpackage is
	// copied only when it is imported or explicitly configured.
	Recursive bool
	// IncludeTests adds _test.go files to the package set and to the copy plan.
	// Their imports are followed like any other, so a test-only dependency
	// enlarges the closure exactly as much as it really does.
	IncludeTests bool
	// PruneFiles are exact repository relative files removed before the closure
	// is computed. They are files, never globs and never directories, because a
	// pattern would let an upstream addition silently change what is removed.
	PruneFiles []string
	// RequiredFiles are exact repository relative files that must survive
	// pruning. An upstream rename then fails the run instead of quietly
	// shrinking the generated module.
	RequiredFiles []string
	// DeniedImports are exact import paths that may never appear in a retained
	// file. Matching is exact, so denying k8s.io/kubernetes/pkg/apis/rbac does
	// not deny its retained /v1 helper subpackage.
	DeniedImports []string
	// AssetGlobs match runtime data that no Go file references statically.
	// Patterns are repository relative and match files only; see MatchGlob for
	// the exact semantics.
	AssetGlobs []string
	// Limits bound the resulting closure. A zero field is unbounded.
	Limits Limits
}

// Limits are observational publication gates.
//
// They never change generated bytes, so they belong outside the replay profile
// hash. Their job is to make an unnoticed upstream refactor that doubles the
// copied surface fail loudly instead of shipping.
type Limits struct {
	// MaxPackages bounds the post-prune package count.
	MaxPackages int
	// MaxFiles bounds the number of files in the post-prune copy plan.
	MaxFiles int
	// MaxNonTestLines bounds the lines in post-prune non-test Go files.
	MaxNonTestLines int
	// MaxPackageGrowth bounds how many packages the closure may reach beyond
	// its seeds, that is post-prune packages minus expanded root packages. It
	// is the limit that notices a newly imported package, which MaxPackages
	// alone would not until the absolute ceiling was hit.
	MaxPackageGrowth int
}

// clone returns a deep copy so a Builder cannot observe a caller mutating the
// slices it was constructed with between passes.
func (o Options) clone() Options {
	out := o
	out.Roots = slices.Clone(o.Roots)
	out.PruneFiles = slices.Clone(o.PruneFiles)
	out.RequiredFiles = slices.Clone(o.RequiredFiles)
	out.DeniedImports = slices.Clone(o.DeniedImports)
	out.AssetGlobs = slices.Clone(o.AssetGlobs)
	return out
}

// normalize sorts the set-like inputs so that two equal option sets produce
// byte identical reports and identical failure ordering.
func (o *Options) normalize() {
	slices.Sort(o.Roots)
	slices.Sort(o.PruneFiles)
	slices.Sort(o.RequiredFiles)
	slices.Sort(o.DeniedImports)
	slices.Sort(o.AssetGlobs)
}

// validate reports every structural problem in one pass.
func (o *Options) validate() error {
	var problems []string
	addf := func(format string, args ...any) {
		problems = append(problems, fmt.Sprintf(format, args...))
	}
	var causes []error
	check := func(field string, err error) {
		if err != nil {
			addf("%s: %v", field, err)
			causes = append(causes, err)
		}
	}

	if strings.TrimSpace(o.Root) == "" {
		addf("root: materialized worktree path is required")
	}
	check("importPrefix", validateImportPath(o.ImportPrefix))

	if len(o.Roots) == 0 {
		addf("roots: at least one package root is required")
	}
	for _, root := range o.Roots {
		check("roots", validateRelPath(root))
	}
	for _, dup := range duplicates(o.Roots) {
		addf("roots: duplicate package root %q", dup)
	}

	for _, file := range o.PruneFiles {
		check("pruneFiles", validateRelFile(file))
	}
	for _, dup := range duplicates(o.PruneFiles) {
		addf("pruneFiles: duplicate entry %q", dup)
	}
	for _, file := range o.RequiredFiles {
		check("requiredFiles", validateRelFile(file))
	}
	for _, dup := range duplicates(o.RequiredFiles) {
		addf("requiredFiles: duplicate entry %q", dup)
	}
	// A path that is both pruned and required is a contradiction the profile
	// author must resolve. Catching it here rather than at removal time means
	// the worktree is never touched before the contradiction is reported.
	for _, file := range o.PruneFiles {
		if slices.Contains(o.RequiredFiles, file) {
			check("pruneFiles", fmt.Errorf("%w: %q", ErrPruneRequired, file))
		}
	}

	for _, imp := range o.DeniedImports {
		check("deniedImports", validateImportPath(imp))
	}
	for _, dup := range duplicates(o.DeniedImports) {
		addf("deniedImports: duplicate entry %q", dup)
	}

	for _, glob := range o.AssetGlobs {
		check("assetGlobs", validateGlob(glob))
	}
	for _, dup := range duplicates(o.AssetGlobs) {
		addf("assetGlobs: duplicate entry %q", dup)
	}

	check("limits.maxPackages", validateLimit(o.Limits.MaxPackages))
	check("limits.maxFiles", validateLimit(o.Limits.MaxFiles))
	check("limits.maxNonTestLines", validateLimit(o.Limits.MaxNonTestLines))
	check("limits.maxPackageGrowth", validateLimit(o.Limits.MaxPackageGrowth))

	if len(problems) == 0 {
		return nil
	}
	return &OptionsError{Problems: problems, errs: causes}
}

// OptionsError reports every problem found in one option set.
type OptionsError struct {
	// Problems are field scoped messages in deterministic order.
	Problems []string
	// errs are the underlying causes. They are unexported and reached through
	// Unwrap so the rendered message stays the only public shape, while
	// errors.Is can still classify any one problem by its sentinel even when
	// several were reported together.
	errs []error
}

// Unwrap exposes every cause so errors.Is can classify a validation failure.
func (e *OptionsError) Unwrap() []error { return e.errs }

// Error renders each problem on its own line.
func (e *OptionsError) Error() string {
	var b strings.Builder
	fmt.Fprintf(&b, "invalid closure options: %d problems", len(e.Problems))
	for _, problem := range e.Problems {
		b.WriteString("\n  - ")
		b.WriteString(problem)
	}
	return b.String()
}

// validateLimit rejects a negative ceiling. Zero is unbounded.
func validateLimit(v int) error {
	if v < 0 {
		return fmt.Errorf("limit must not be negative, got %d", v)
	}
	return nil
}

// validateRelPath checks that p is a clean, relative, traversal free slash path
// naming a directory or file inside the materialized root.
//
// This repeats a little of internal/config on purpose: closure must stay usable
// without a profile, and the two validators answer different questions. Config
// asks whether an operator may write a path; this asks whether the engine may
// touch one.
func validateRelPath(p string) error {
	switch {
	case p == "":
		return errors.New("path must not be empty")
	case strings.TrimSpace(p) != p:
		return errors.New("path must not have leading or trailing space")
	case strings.ContainsRune(p, '\x00'):
		return errors.New("path must not contain a null byte")
	case strings.ContainsRune(p, '\\'):
		return errors.New("path must use forward slashes")
	case strings.HasPrefix(p, "/"):
		return errors.New("path must be relative")
	}
	// Traversal is checked before cleanliness because a path that already leaves
	// the root, such as "../escape", is its own clean form and would otherwise
	// pass every remaining check.
	if p == ".." || strings.HasPrefix(p, "../") || strings.Contains(p, "/../") || strings.HasSuffix(p, "/..") {
		return errors.New("path must not traverse parent directories")
	}
	if p == "." {
		return errors.New("path must name a file or directory")
	}
	for _, r := range p {
		if r < 0x20 || r == 0x7f {
			return errors.New("path must not contain control characters")
		}
	}
	if p != path.Clean(p) {
		return errors.New("path must be in clean slash form")
	}
	return nil
}

// validateRelFile checks a path that must name a file rather than a directory.
func validateRelFile(p string) error {
	if err := validateRelPath(p); err != nil {
		return err
	}
	if strings.HasSuffix(p, "/") {
		return errors.New("path must name a file, not a directory")
	}
	return nil
}

// validateImportPath checks a Go import path. The check is intentionally
// shallow: the engine compares import paths for exact equality and prefix
// membership, and never resolves them through the module proxy.
func validateImportPath(p string) error {
	switch {
	case p == "":
		return errors.New("import path must not be empty")
	case strings.TrimSpace(p) != p:
		return errors.New("import path must not have leading or trailing space")
	case strings.HasPrefix(p, "/") || strings.HasSuffix(p, "/"):
		return errors.New("import path must not start or end with a slash")
	case strings.Contains(p, "//"):
		return errors.New("import path must not contain an empty element")
	}
	for _, elem := range strings.Split(p, "/") {
		if elem == "." || elem == ".." {
			return errors.New("import path must not contain a relative element")
		}
	}
	for _, r := range p {
		if r <= ' ' || r == 0x7f || r == '"' || r == '\\' {
			return fmt.Errorf("import path contains unsupported character %q", r)
		}
	}
	return nil
}

// validateGlob checks an asset or go:embed pattern.
func validateGlob(p string) error {
	// A pattern that is not a clean relative path is reported as a malformed
	// pattern rather than as a malformed path, because the caller's context is
	// always a glob and callers classify with ErrPatternMalformed.
	if err := validateRelPath(p); err != nil {
		return fmt.Errorf("%w: %w", ErrPatternMalformed, err)
	}
	if strings.Contains(p, "**") {
		return fmt.Errorf("%w: %q", ErrRecursivePattern, p)
	}
	for _, elem := range strings.Split(p, "/") {
		if _, err := path.Match(elem, "probe"); err != nil {
			return fmt.Errorf("%w: %q: %w", ErrPatternMalformed, p, err)
		}
	}
	return nil
}

// duplicates reports the values that appear more than once, in sorted order.
func duplicates(values []string) []string {
	seen := make(map[string]bool, len(values))
	var dups []string
	for _, v := range values {
		if seen[v] && !slices.Contains(dups, v) {
			dups = append(dups, v)
		}
		seen[v] = true
	}
	slices.Sort(dups)
	return dups
}
