package closure

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io/fs"
	"slices"
	"strconv"
	"strings"
)

// Result is one complete closure build.
type Result struct {
	// Packages are the post-prune materialized packages, sorted by import path.
	Packages []Package
	// CopyPlan lists every file a portable build needs, sorted by path.
	CopyPlan []CopyEntry
	// RemovedFiles are the prune entries this pass removed from the worktree.
	// A later pass over an already pruned tree removes nothing and reports an
	// empty list, which is how the pipeline recognises a fixed point.
	RemovedFiles []string
	// Report is the deterministic, encodable summary of the build.
	Report ClosureReport
}

// Package is one materialized package in the post-prune closure.
type Package struct {
	// ImportPath is the package path inside the source module.
	ImportPath string
	// Dir is the package directory relative to the materialized root.
	Dir string
	// Name is the Go package name its files declare.
	Name string
	// GoFiles are the package's non-test Go files, sorted.
	GoFiles []string
	// TestFiles are the package's _test.go files, sorted. It is empty unless
	// tests were included.
	TestFiles []string
	// Imports are every import the package's retained files declare, sorted.
	Imports []string
}

// ClosureReport is the encodable shape of one build.
//
// The two halves are kept apart on purpose. Exact holds the invariants a
// generated release is allowed to depend on: change one of them and the
// published module changes. Observed holds measurements that gate publication
// but never alter a generated byte, which is why they stay out of the replay
// profile hash and why a golden may compare them with tolerance while comparing
// Exact literally.
type ClosureReport struct {
	Exact    ExactShape    `json:"exact"`
	Observed ObservedShape `json:"observed"`
}

// ExactShape is the part of a closure that must not drift silently.
type ExactShape struct {
	// ImportPrefix is the source module path whose imports were followed.
	ImportPrefix string `json:"importPrefix"`
	// Roots are the expanded seed package directories, sorted.
	Roots []string `json:"roots"`
	// Packages are the post-prune package import paths, sorted.
	Packages []string `json:"packages"`
	// Files are every copy plan path, sorted.
	Files []string `json:"files"`
	// ExternalPackages are boundary imports that resolve to real module
	// dependencies, sorted. They are what the dependency policy reasons about.
	ExternalPackages []string `json:"externalPackages"`
	// StandardPackages are boundary imports satisfied by the standard library,
	// sorted. They never become module dependencies.
	StandardPackages []string `json:"standardPackages"`
	// PrunedFiles are the exact prune entries asserted by this build, sorted.
	PrunedFiles []string `json:"prunedFiles"`
	// DeniedImports are the exact import paths proved absent, sorted.
	DeniedImports []string `json:"deniedImports"`
}

// ObservedShape is the measured size of a closure.
type ObservedShape struct {
	// PrePrune measures the closure as found, before this pass pruned it.
	PrePrune Counts `json:"prePrune"`
	// PostPrune measures the closure the build produced.
	PostPrune Counts `json:"postPrune"`
	// Growth holds the deltas the limits are expressed against.
	Growth Growth `json:"growth"`
}

// Counts measures one closure.
type Counts struct {
	// Packages is the number of materialized packages.
	Packages int `json:"packages"`
	// GoFiles is the number of Go files those packages hold.
	GoFiles int `json:"goFiles"`
	// Files is the number of copy plan entries, so Go files plus native
	// sources, headers, objects, embedded data, and matched assets.
	Files int `json:"files"`
	// NonTestLines is the total line count of non-test Go files.
	NonTestLines int `json:"nonTestLines"`
}

// Growth holds the deltas a run is judged by.
type Growth struct {
	// RootPackages is the number of expanded seed packages.
	RootPackages int `json:"rootPackages"`
	// PackagesBeyondRoots is post-prune packages minus RootPackages. This is
	// the value limits.maxPackageGrowth bounds: it notices a newly imported
	// package immediately, where an absolute package ceiling would not react
	// until the closure had grown several times over.
	PackagesBeyondRoots int `json:"packagesBeyondRoots"`
	// PackagesRemoved is how many packages pruning dropped from the closure.
	PackagesRemoved int `json:"packagesRemoved"`
	// GoFilesRemoved is how many Go files pruning dropped.
	GoFilesRemoved int `json:"goFilesRemoved"`
	// FilesRemoved is how many copy plan entries pruning dropped.
	FilesRemoved int `json:"filesRemoved"`
	// NonTestLinesRemoved is how many non-test Go lines pruning dropped.
	NonTestLinesRemoved int `json:"nonTestLinesRemoved"`
}

// JSON renders the report as deterministic, indented bytes with a trailing
// newline, which is the form a checked-in golden takes.
//
// Every list the report carries is sorted and non-nil at construction, so the
// encoding depends on the closure alone and never on map iteration order or on
// whether a list happened to be empty.
func (r ClosureReport) JSON() ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(r); err != nil {
		return nil, fmt.Errorf("encode closure report: %w", err)
	}
	return buf.Bytes(), nil
}

// MarshalJSON renders a copy entry with its mode as an octal string, so a
// golden shows 0644 rather than the decimal 420 an fs.FileMode would encode to.
func (e CopyEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(copyEntryJSON{
		Path: e.Path,
		Kind: string(e.Kind),
		Mode: "0" + strconv.FormatUint(uint64(e.Mode.Perm()), 8),
	})
}

// UnmarshalJSON restores a copy entry written by MarshalJSON.
func (e *CopyEntry) UnmarshalJSON(data []byte) error {
	var raw copyEntryJSON
	if err := json.Unmarshal(data, &raw); err != nil {
		return fmt.Errorf("decode copy entry: %w", err)
	}
	mode, err := strconv.ParseUint(raw.Mode, 8, 32)
	if err != nil {
		return fmt.Errorf("decode copy entry mode %q: %w", raw.Mode, err)
	}
	e.Path = raw.Path
	e.Kind = CopyKind(raw.Kind)
	e.Mode = fs.FileMode(mode).Perm()
	return nil
}

// copyEntryJSON is the wire shape of a copy plan entry.
type copyEntryJSON struct {
	Path string `json:"path"`
	Kind string `json:"kind"`
	Mode string `json:"mode"`
}

// newPackages renders a scanned closure as the exported package list.
func newPackages(set *closureSet) []Package {
	out := make([]Package, 0, len(set.dirs))
	for _, dir := range set.dirs {
		pkg := set.packages[dir]
		goFiles := make([]string, 0, len(pkg.goFiles))
		testFiles := make([]string, 0)
		for _, file := range pkg.goFiles {
			if file.test {
				testFiles = append(testFiles, file.path)
				continue
			}
			goFiles = append(goFiles, file.path)
		}
		slices.Sort(goFiles)
		slices.Sort(testFiles)
		out = append(out, Package{
			ImportPath: pkg.importPath,
			Dir:        displayPath(pkg.dir),
			Name:       pkg.name,
			GoFiles:    goFiles,
			TestFiles:  testFiles,
			Imports:    pkg.imports(),
		})
	}
	slices.SortFunc(out, func(a, b Package) int {
		return strings.Compare(a.ImportPath, b.ImportPath)
	})
	return out
}

// planPaths lists a copy plan's paths in sorted order.
func planPaths(plan []CopyEntry) []string {
	out := make([]string, 0, len(plan))
	for _, entry := range plan {
		out = append(out, entry.Path)
	}
	slices.Sort(out)
	return out
}

// countClosure measures one closure and its copy plan.
func countClosure(set *closureSet, plan []CopyEntry) Counts {
	return Counts{
		Packages:     len(set.dirs),
		GoFiles:      set.goFileCount(),
		Files:        len(plan),
		NonTestLines: set.nonTestLines(),
	}
}

// cloneStrings copies a list, returning an empty list rather than nil so the
// report encodes [] instead of null. A golden that flips between null and []
// when a profile stops pruning is noise a reviewer has to read past.
func cloneStrings(values []string) []string {
	out := make([]string, len(values))
	copy(out, values)
	return out
}
