/*
Copyright 2014 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by soapbox. DO NOT EDIT.
// This module-local compatibility declaration is intentionally not type-compatible with k8s.io/apiserver.
// Upstream repository: https://github.com/kubernetes/kubernetes.git
// Upstream path: staging/src/k8s.io/apiserver/pkg/authorization/authorizer/interfaces.go
// Upstream commit: 24e2b02af5543d7910c2bb074c7264df5a8f0467

package authorizer

import (
	"context"
	"fmt"

	"monis.app/kk/rbac_authorizer/internal/kk/compat/apiserver/user"
)

// Attributes is the request surface retained RBAC evaluation reads.
type Attributes interface {
	GetUser() user.Info
	GetVerb() string
	GetNamespace() string
	GetResource() string
	GetSubresource() string
	GetName() string
	GetAPIGroup() string
	IsResourceRequest() bool
	GetPath() string
}

// AttributesRecord is a directly constructible module-local request record.
type AttributesRecord struct {
	User user.Info
	Verb string
	Namespace string
	APIGroup string
	APIVersion string
	Resource string
	Subresource string
	Name string
	ResourceRequest bool
	Path string
}

func (a AttributesRecord) GetUser() user.Info { return a.User }
func (a AttributesRecord) GetVerb() string { return a.Verb }
func (a AttributesRecord) GetNamespace() string { return a.Namespace }
func (a AttributesRecord) GetResource() string { return a.Resource }
func (a AttributesRecord) GetSubresource() string { return a.Subresource }
func (a AttributesRecord) GetName() string { return a.Name }
func (a AttributesRecord) GetAPIGroup() string { return a.APIGroup }
func (a AttributesRecord) IsResourceRequest() bool { return a.ResourceRequest }
func (a AttributesRecord) GetPath() string { return a.Path }

// Decision is a module-local authorization verdict.
type Decision int

const (
	DecisionDeny Decision = iota
	DecisionAllow
	DecisionNoOpinion
)

func (d Decision) String() string {
	switch d {
	case DecisionDeny:
		return "Deny"
	case DecisionAllow:
		return "Allow"
	case DecisionNoOpinion:
		return "NoOpinion"
	default:
		return fmt.Sprintf("Unknown (%d)", int(d))
	}
}

// Authorizer makes a module-local authorization decision.
type Authorizer interface {
	Authorize(context.Context, Attributes) (Decision, string, error)
}

// RuleResolver resolves module-local rule information for a user.
type RuleResolver interface {
	RulesFor(context.Context, user.Info, string) ([]ResourceRuleInfo, []NonResourceRuleInfo, bool, error)
}
