/*
Copyright 2014 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by soapbox. DO NOT EDIT.
// This module-local compatibility declaration is intentionally not type-compatible with k8s.io/apiserver.
// Upstream repository: https://github.com/kubernetes/kubernetes.git
// Upstream path: staging/src/k8s.io/apiserver/pkg/authorization/authorizer/rule.go
// Upstream commit: 24e2b02af5543d7910c2bb074c7264df5a8f0467

package authorizer

// ResourceRuleInfo describes allowed resource operations.
type ResourceRuleInfo interface {
	GetVerbs() []string
	GetAPIGroups() []string
	GetResources() []string
	GetResourceNames() []string
}

// DefaultResourceRuleInfo is the module-local resource rule record.
type DefaultResourceRuleInfo struct {
	Verbs []string
	APIGroups []string
	Resources []string
	ResourceNames []string
}

func (i *DefaultResourceRuleInfo) GetVerbs() []string { return i.Verbs }
func (i *DefaultResourceRuleInfo) GetAPIGroups() []string { return i.APIGroups }
func (i *DefaultResourceRuleInfo) GetResources() []string { return i.Resources }
func (i *DefaultResourceRuleInfo) GetResourceNames() []string { return i.ResourceNames }

// NonResourceRuleInfo describes allowed non-resource operations.
type NonResourceRuleInfo interface {
	GetVerbs() []string
	GetNonResourceURLs() []string
}

// DefaultNonResourceRuleInfo is the module-local non-resource rule record.
type DefaultNonResourceRuleInfo struct {
	Verbs []string
	NonResourceURLs []string
}

func (i *DefaultNonResourceRuleInfo) GetVerbs() []string { return i.Verbs }
func (i *DefaultNonResourceRuleInfo) GetNonResourceURLs() []string { return i.NonResourceURLs }
