package relocate_test

import (
	"context"
	"errors"
	"io/fs"
	"slices"
	"strings"
	"testing"

	"github.com/enj/soapbox/tools/internal/config"
	"github.com/enj/soapbox/tools/internal/relocate"
)

const internalPrefix = "internal/kk"

// regular builds a plan entry for an ordinary source file.
func regular(pkg, name, contents string) relocate.PlanFile {
	return relocate.PlanFile{
		Path:     pkg + "/" + name,
		Package:  pkg,
		Mode:     relocate.ModeRegular,
		Contents: []byte(contents),
	}
}

// paths reports the destination paths of a relocated set.
func paths(set relocate.FileSet) []string {
	names := make([]string, len(set.Files))
	for i, file := range set.Files {
		names[i] = file.Path
	}
	return names
}

func TestBuildPreservesUpstreamPaths(t *testing.T) {
	t.Parallel()

	plan := relocate.Plan{Files: []relocate.PlanFile{
		regular("pkg/registry/rbac/validation", "rule.go", "package validation\n"),
		regular("plugin/pkg/auth/authorizer/rbac", "rbac.go", "package rbac\n"),
		regular("pkg/apis/rbac/v1", "doc.go", "package v1\n"),
		regular("pkg/apis/rbac/v1", "evaluation_helpers.go", "package v1\n"),
	}}

	set, err := relocate.Build(t.Context(), plan, relocate.Options{InternalPrefix: internalPrefix})
	if err != nil {
		t.Fatalf("build: %v", err)
	}

	// Every upstream element survives below the internal prefix, which is what
	// keeps nested internal visibility working in the generated module.
	want := []string{
		"internal/kk/pkg/apis/rbac/v1/doc.go",
		"internal/kk/pkg/apis/rbac/v1/evaluation_helpers.go",
		"internal/kk/pkg/registry/rbac/validation/rule.go",
		"internal/kk/plugin/pkg/auth/authorizer/rbac/rbac.go",
	}
	if got := paths(set); !slices.Equal(got, want) {
		t.Errorf("relocated to %v, want %v", got, want)
	}

	wantPackages := []string{
		"internal/kk/pkg/apis/rbac/v1",
		"internal/kk/pkg/registry/rbac/validation",
		"internal/kk/plugin/pkg/auth/authorizer/rbac",
	}
	got := make([]string, len(set.Packages))
	for i, pkg := range set.Packages {
		got[i] = pkg.Path
	}
	if !slices.Equal(got, wantPackages) {
		t.Errorf("packages %v, want %v", got, wantPackages)
	}
	if files := set.Packages[0].Files; len(files) != 2 {
		t.Errorf("first package holds %v, want both v1 files", files)
	}
	if set.Packages[0].Source != "pkg/apis/rbac/v1" {
		t.Errorf("first package records source %q", set.Packages[0].Source)
	}

	file, ok := set.Lookup("internal/kk/pkg/apis/rbac/v1/doc.go")
	if !ok {
		t.Fatal("lookup found no relocated doc.go")
	}
	if file.Source != "pkg/apis/rbac/v1/doc.go" || file.SourcePackage != "pkg/apis/rbac/v1" {
		t.Errorf("relocated file lost its upstream identity: %+v", file)
	}
}

// TestBuildIsDeterministic asserts that plan order cannot reach the output. The
// closure walks packages through maps, so two runs may hand over the same files
// in different orders, and both must relocate to the identical set.
func TestBuildIsDeterministic(t *testing.T) {
	t.Parallel()

	files := []relocate.PlanFile{
		regular("pkg/apis/rbac/v1", "doc.go", "package v1\n"),
		regular("plugin/pkg/auth/authorizer/rbac", "rbac.go", "package rbac\n"),
		regular("pkg/registry/rbac/validation", "rule.go", "package validation\n"),
		regular("pkg/apis/rbac/v1", "evaluation_helpers.go", "package v1\n"),
	}

	var want []string
	for shift := range len(files) {
		rotated := append(slices.Clone(files[shift:]), files[:shift]...)
		set, err := relocate.Build(t.Context(), relocate.Plan{Files: rotated}, relocate.Options{InternalPrefix: internalPrefix})
		if err != nil {
			t.Fatalf("build: %v", err)
		}
		got := paths(set)
		if want == nil {
			want = got
			continue
		}
		if !slices.Equal(got, want) {
			t.Fatalf("rotation %d relocated to %v, want %v", shift, got, want)
		}
	}
}

func TestBuildGeneratedFilesKeepTheirFlag(t *testing.T) {
	t.Parallel()

	plan := relocate.Plan{Files: []relocate.PlanFile{
		{
			Path:      "pkg/apis/rbac/v1/zz_generated.deepcopy.go",
			Package:   "pkg/apis/rbac/v1",
			Mode:      relocate.ModeRegular,
			Contents:  []byte("// Code generated by deepcopy-gen. DO NOT EDIT.\n"),
			Generated: true,
		},
		regular("pkg/apis/rbac/v1", "doc.go", "package v1\n"),
	}}

	set, err := relocate.Build(t.Context(), plan, relocate.Options{InternalPrefix: internalPrefix})
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	generated, ok := set.Lookup("internal/kk/pkg/apis/rbac/v1/zz_generated.deepcopy.go")
	if !ok {
		t.Fatal("lookup found no relocated generated file")
	}
	if !generated.Generated {
		t.Error("relocation lost the generated flag")
	}
	plain, _ := set.Lookup("internal/kk/pkg/apis/rbac/v1/doc.go")
	if plain.Generated {
		t.Error("relocation invented a generated flag")
	}
}

func TestBuildExecutableModeSurvives(t *testing.T) {
	t.Parallel()

	plan := relocate.Plan{Files: []relocate.PlanFile{{
		Path:     "hack/tool.sh",
		Package:  "hack",
		Mode:     relocate.ModeExecutable,
		Contents: []byte("#!/bin/sh\n"),
	}}}

	set, err := relocate.Build(t.Context(), plan, relocate.Options{InternalPrefix: internalPrefix})
	if err != nil {
		t.Fatalf("build: %v", err)
	}
	if set.Files[0].Mode != relocate.ModeExecutable {
		t.Errorf("mode %v, want executable", set.Files[0].Mode)
	}
	if got := set.Files[0].Mode.String(); got != "100755" {
		t.Errorf("mode renders as %q, want the git octal form", got)
	}
}

func TestBuildRejects(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name   string
		plan   relocate.Plan
		prefix string
		want   error
	}{
		{
			name:   "prefix without an internal element",
			plan:   relocate.Plan{Files: []relocate.PlanFile{regular("pkg/a", "a.go", "")}},
			prefix: "vendor/kk",
			want:   relocate.ErrPrefix,
		},
		{
			name:   "absolute prefix",
			plan:   relocate.Plan{Files: []relocate.PlanFile{regular("pkg/a", "a.go", "")}},
			prefix: "/internal/kk",
			want:   relocate.ErrPrefix,
		},
		{
			name:   "prefix that traverses",
			plan:   relocate.Plan{Files: []relocate.PlanFile{regular("pkg/a", "a.go", "")}},
			prefix: "../internal/kk",
			want:   relocate.ErrPrefix,
		},
		{
			name: "path that traverses",
			plan: relocate.Plan{Files: []relocate.PlanFile{{
				Path:    "../../etc/passwd",
				Package: "..",
				Mode:    relocate.ModeRegular,
			}}},
			want: config.ErrPathTraversal,
		},
		{
			name: "file from a subdirectory of its package",
			plan: relocate.Plan{Files: []relocate.PlanFile{{
				Path:    "pkg/apis/rbac/v1/doc.go",
				Package: "pkg/apis/rbac",
				Mode:    relocate.ModeRegular,
			}}},
			want: relocate.ErrPackageBoundary,
		},
		{
			name: "unsupported mode",
			plan: relocate.Plan{Files: []relocate.PlanFile{{
				Path:    "pkg/a/a.go",
				Package: "pkg/a",
				Mode:    relocate.Mode(9),
			}}},
			want: relocate.ErrUnsupportedMode,
		},
		{
			name: "collision",
			plan: relocate.Plan{Files: []relocate.PlanFile{
				regular("pkg/a", "a.go", "first"),
				regular("pkg/a", "a.go", "second"),
			}},
			want: relocate.ErrCollision,
		},
		{
			name: "destination overlap",
			plan: relocate.Plan{Files: []relocate.PlanFile{
				regular("pkg/a", "b", "a file named like a directory"),
				regular("pkg/a/b", "c.go", "package b"),
			}},
			want: relocate.ErrOverlap,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			prefix := test.prefix
			if prefix == "" {
				prefix = internalPrefix
			}
			_, err := relocate.Build(t.Context(), test.plan, relocate.Options{InternalPrefix: prefix})
			if err == nil {
				t.Fatal("build accepted the plan")
			}
			if !errors.Is(err, test.want) {
				t.Errorf("build error %v, want %v", err, test.want)
			}
		})
	}
}

func TestBuildSymlinkPolicy(t *testing.T) {
	t.Parallel()

	link := func(target string) relocate.PlanFile {
		return relocate.PlanFile{
			Path:     "pkg/a/link.go",
			Package:  "pkg/a",
			Mode:     relocate.ModeSymlink,
			Contents: []byte(target),
		}
	}
	sibling := regular("pkg/a", "real.go", "package a\n")
	cousin := regular("pkg/b", "real.go", "package b\n")

	tests := []struct {
		name    string
		policy  relocate.SymlinkPolicy
		files   []relocate.PlanFile
		wantErr bool
	}{
		{
			name:    "rejected by default",
			files:   []relocate.PlanFile{sibling, link("real.go")},
			wantErr: true,
		},
		{
			name:   "internal target in the same package",
			policy: relocate.SymlinkInternal,
			files:  []relocate.PlanFile{sibling, link("real.go")},
		},
		{
			name:   "internal target in another package",
			policy: relocate.SymlinkInternal,
			files:  []relocate.PlanFile{cousin, link("../b/real.go")},
		},
		{
			name:    "target that escapes the destination root",
			policy:  relocate.SymlinkInternal,
			files:   []relocate.PlanFile{sibling, link("../../../../etc/passwd")},
			wantErr: true,
		},
		{
			name:    "absolute target",
			policy:  relocate.SymlinkInternal,
			files:   []relocate.PlanFile{sibling, link("/etc/passwd")},
			wantErr: true,
		},
		{
			name:    "target outside the relocated set",
			policy:  relocate.SymlinkInternal,
			files:   []relocate.PlanFile{sibling, link("absent.go")},
			wantErr: true,
		},
		{
			name:    "empty target",
			policy:  relocate.SymlinkInternal,
			files:   []relocate.PlanFile{sibling, link("")},
			wantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			_, err := relocate.Build(t.Context(), relocate.Plan{Files: test.files}, relocate.Options{
				InternalPrefix: internalPrefix,
				Symlinks:       test.policy,
			})
			switch {
			case test.wantErr && !errors.Is(err, relocate.ErrSymlink):
				t.Errorf("build error %v, want %v", err, relocate.ErrSymlink)
			case !test.wantErr && err != nil:
				t.Errorf("build: %v", err)
			}
		})
	}
}

// TestBuildSymlinkChains covers a link whose target is itself a link. The chain
// has to end at a file the set carries, so a cycle is refused rather than
// materialized into a tree where every read of the file fails with ELOOP.
func TestBuildSymlinkChains(t *testing.T) {
	t.Parallel()

	link := func(name, target string) relocate.PlanFile {
		return relocate.PlanFile{
			Path:     "pkg/a/" + name,
			Package:  "pkg/a",
			Mode:     relocate.ModeSymlink,
			Contents: []byte(target),
		}
	}
	target := regular("pkg/a", "real.go", "package a\n")
	script := relocate.PlanFile{
		Path:     "pkg/a/tool.sh",
		Package:  "pkg/a",
		Mode:     relocate.ModeExecutable,
		Contents: []byte("#!/bin/sh\n"),
	}

	tests := []struct {
		name    string
		files   []relocate.PlanFile
		wantErr bool
	}{
		{
			name:  "chain that ends at a regular file",
			files: []relocate.PlanFile{target, link("x.go", "y.go"), link("y.go", "real.go")},
		},
		{
			name:  "chain that ends at an executable",
			files: []relocate.PlanFile{script, link("x.go", "y.go"), link("y.go", "tool.sh")},
		},
		{
			name:  "chain that ends after several hops",
			files: []relocate.PlanFile{target, link("w.go", "x.go"), link("x.go", "y.go"), link("y.go", "real.go")},
		},
		{
			name:    "link to itself",
			files:   []relocate.PlanFile{link("x.go", "x.go")},
			wantErr: true,
		},
		{
			name:    "two link cycle",
			files:   []relocate.PlanFile{link("x.go", "y.go"), link("y.go", "x.go")},
			wantErr: true,
		},
		{
			name:    "three link cycle",
			files:   []relocate.PlanFile{link("x.go", "y.go"), link("y.go", "z.go"), link("z.go", "x.go")},
			wantErr: true,
		},
		{
			name:    "chain that enters a cycle it is not part of",
			files:   []relocate.PlanFile{link("w.go", "x.go"), link("x.go", "y.go"), link("y.go", "x.go")},
			wantErr: true,
		},
		{
			name:    "chain that ends outside the set",
			files:   []relocate.PlanFile{link("x.go", "y.go"), link("y.go", "absent.go")},
			wantErr: true,
		},
		{
			name:    "chain that escapes the destination root",
			files:   []relocate.PlanFile{link("x.go", "y.go"), link("y.go", "../../../../etc/passwd")},
			wantErr: true,
		},
		{
			name:    "chain that reaches an absolute target",
			files:   []relocate.PlanFile{link("x.go", "y.go"), link("y.go", "/etc/passwd")},
			wantErr: true,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			_, err := relocate.Build(t.Context(), relocate.Plan{Files: test.files}, relocate.Options{
				InternalPrefix: internalPrefix,
				Symlinks:       relocate.SymlinkInternal,
			})
			switch {
			case test.wantErr && !errors.Is(err, relocate.ErrSymlink):
				t.Errorf("build error %v, want %v", err, relocate.ErrSymlink)
			case !test.wantErr && err != nil:
				t.Errorf("build: %v", err)
			}
		})
	}
}

// TestBuildRejectsCaseCollisions covers destinations that a case insensitive
// file system cannot tell apart. Rejecting them is what keeps the generated
// module identical for a consumer on macOS or Windows, where checking out both
// files produces one.
func TestBuildRejectsCaseCollisions(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name  string
		files []relocate.PlanFile
		want  error
	}{
		{
			name: "file names differing only in case",
			files: []relocate.PlanFile{
				regular("pkg/a", "File.go", "package a\n"),
				regular("pkg/a", "file.go", "package a\n"),
			},
			want: relocate.ErrCaseCollision,
		},
		{
			name: "directory names differing only in case",
			files: []relocate.PlanFile{
				regular("pkg/A", "doc.go", "package a\n"),
				regular("pkg/a", "doc.go", "package a\n"),
			},
			want: relocate.ErrCaseCollision,
		},
		{
			name: "extension differing only in case",
			files: []relocate.PlanFile{
				regular("pkg/a", "doc.go", "package a\n"),
				regular("pkg/a", "doc.GO", "package a\n"),
			},
			want: relocate.ErrCaseCollision,
		},
		{
			name: "file that is a directory of another under folding",
			files: []relocate.PlanFile{
				regular("pkg/a", "B", "a file named like a directory"),
				regular("pkg/a/b", "c.go", "package b\n"),
			},
			want: relocate.ErrOverlap,
		},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			_, err := relocate.Build(t.Context(), relocate.Plan{Files: test.files}, relocate.Options{
				InternalPrefix: internalPrefix,
			})
			if !errors.Is(err, test.want) {
				t.Fatalf("build error %v, want %v", err, test.want)
			}
			// A collision is a profile bug, so the report has to name both
			// upstream files. Naming only the destination would leave an
			// operator without the two selections that have to be reconciled.
			for _, file := range test.files {
				if !strings.Contains(err.Error(), file.Path) {
					t.Errorf("error %v does not name upstream file %q", err, file.Path)
				}
			}
		})
	}
}

// TestBuildRejectsNonASCIIPaths pins the reason a destination cannot hold two
// paths that differ only by a Unicode case folding: such a path never reaches a
// destination at all. Folding is still defined over Unicode, which
// TestFoldPath covers, so the rule stays right if path validation ever widens.
func TestBuildRejectsNonASCIIPaths(t *testing.T) {
	t.Parallel()

	_, err := relocate.Build(t.Context(), relocate.Plan{Files: []relocate.PlanFile{
		// U+212A KELVIN SIGN folds together with the ASCII k.
		regular("pkg/a", "Kelvin.go", "package a\n"),
	}}, relocate.Options{InternalPrefix: internalPrefix})
	if err == nil {
		t.Fatal("build accepted a non ASCII destination path")
	}
}

// TestBuildRejectionIsDeterministic asserts that plan order cannot reach a
// diagnostic either. A profile bug that named its two files one way round on
// one run and the other way round on the next would look like two bugs.
func TestBuildRejectionIsDeterministic(t *testing.T) {
	t.Parallel()

	colliding := []relocate.PlanFile{
		regular("pkg/a", "a.go", "first"),
		regular("pkg/a", "a.go", "second"),
	}
	folding := []relocate.PlanFile{
		regular("pkg/a", "File.go", "package a\n"),
		regular("pkg/a", "file.go", "package a\n"),
	}

	for _, plan := range [][]relocate.PlanFile{colliding, folding} {
		_, forward := relocate.Build(t.Context(), relocate.Plan{Files: plan}, relocate.Options{InternalPrefix: internalPrefix})
		reversed := []relocate.PlanFile{plan[1], plan[0]}
		_, backward := relocate.Build(t.Context(), relocate.Plan{Files: reversed}, relocate.Options{InternalPrefix: internalPrefix})
		switch {
		case forward == nil || backward == nil:
			t.Fatalf("build accepted %v", plan)
		case forward.Error() != backward.Error():
			t.Errorf("plan order changed the report:\n%v\n%v", forward, backward)
		}
	}
}

func TestBuildHonoursCancellation(t *testing.T) {
	t.Parallel()

	ctx, cancel := context.WithCancel(t.Context())
	cancel()

	_, err := relocate.Build(ctx, relocate.Plan{}, relocate.Options{InternalPrefix: internalPrefix})
	if !errors.Is(err, context.Canceled) {
		t.Errorf("build error %v, want %v", err, context.Canceled)
	}
}

// TestModeOf covers the classification a copy plan's file system modes go
// through on the way into a relocated set.
func TestModeOf(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name    string
		mode    fs.FileMode
		want    relocate.Mode
		wantErr bool
	}{
		{name: "regular", mode: 0o644, want: relocate.ModeRegular},
		{name: "read only regular", mode: 0o444, want: relocate.ModeRegular},
		{name: "executable", mode: 0o755, want: relocate.ModeExecutable},
		{name: "group executable only", mode: 0o645, want: relocate.ModeExecutable},
		{name: "symlink", mode: fs.ModeSymlink | 0o777, want: relocate.ModeSymlink},
		{name: "directory", mode: fs.ModeDir | 0o755, wantErr: true},
		{name: "device", mode: fs.ModeDevice | 0o644, wantErr: true},
		{name: "socket", mode: fs.ModeSocket | 0o644, wantErr: true},
		{name: "named pipe", mode: fs.ModeNamedPipe | 0o644, wantErr: true},
		{name: "setuid", mode: fs.ModeSetuid | 0o755, wantErr: true},
		{name: "setgid", mode: fs.ModeSetgid | 0o755, wantErr: true},
		{name: "sticky", mode: fs.ModeSticky | 0o644, wantErr: true},
	}

	for _, test := range tests {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			got, err := relocate.ModeOf(test.mode)
			switch {
			case test.wantErr && !errors.Is(err, relocate.ErrUnsupportedMode):
				t.Errorf("classify error %v, want %v", err, relocate.ErrUnsupportedMode)
			case !test.wantErr && err != nil:
				t.Errorf("classify: %v", err)
			case !test.wantErr && got != test.want:
				t.Errorf("classified as %v, want %v", got, test.want)
			}
		})
	}
}
